// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.vet;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import org.springframework.samples.petclinic.model.Specialty;

import java.util.HashSet;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.Mockito.when;

public class Vet_addSpecialty_76f550ca81_Test {

    @Mock
    private Vet vet;

    @BeforeEach
    public void setup() {
        MockitoAnnotations.initMocks(this);
        when(vet.getSpecialtiesInternal()).thenReturn(new HashSet<>());
    }

    @Test
    public void testAddSpecialtySuccess() {
        Specialty specialty = new Specialty();
        specialty.setName("TestSpecialty");
        vet.addSpecialty(specialty);
        assertTrue(vet.getSpecialtiesInternal().contains(specialty));
    }

    @Test
    public void testAddSpecialtyFailure() {
        Specialty specialty = new Specialty();
        specialty.setName("TestSpecialty");
        vet.addSpecialty(specialty);
        Specialty specialty2 = new Specialty();
        specialty2.setName("TestSpecialty2");
        assertFalse(vet.getSpecialtiesInternal().contains(specialty2));
    }
}
