// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.vet;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.samples.petclinic.model.Specialty;
import java.util.Set;

public class Vet_getSpecialtiesInternal_ce2cc1ae59_Test {

    private Vet vet;

    @BeforeEach
    public void setUp() {
        vet = new Vet();
    }

    @Test
    public void testGetSpecialtiesInternalWhenSpecialtiesIsNull() {
        Set<Specialty> specialties = vet.getSpecialtiesInternal();
        assertTrue(specialties.isEmpty(), "The specialties set should be empty");
    }

    @Test
    public void testGetSpecialtiesInternalWhenSpecialtiesIsNotNull() {
        Specialty specialty = new Specialty();
        specialty.setName("surgery");
        vet.addSpecialty(specialty);

        Set<Specialty> specialties = vet.getSpecialtiesInternal();
        assertEquals(1, specialties.size(), "The specialties set should contain one element");
        assertTrue(specialties.contains(specialty), "The specialties set should contain the added specialty");
    }
}
