// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.vet;

import java.util.HashSet;
import java.util.Set;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.samples.petclinic.model.Specialty;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

public class Vet_addSpecialty_76f550ca81_Test {

    private Vet vet;
    private Specialty specialty;

    @BeforeEach
    public void setup() {
        vet = new Vet();
        specialty = new Specialty();
        specialty.setName("Cardiology");
    }

    @Test
    public void testAddSpecialty() {
        vet.addSpecialty(specialty);
        Set<Specialty> specialties = vet.getSpecialties();
        assertTrue(specialties.contains(specialty));
    }

    @Test
    public void testAddSpecialtyWhenSpecialtiesIsNull() {
        vet.setSpecialtiesInternal(null);
        vet.addSpecialty(specialty);
        Set<Specialty> specialties = vet.getSpecialties();
        assertTrue(specialties.contains(specialty));
    }
}
