// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.vet;

import java.util.HashSet;
import java.util.Set;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.samples.petclinic.model.Specialty;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;

public class Vet_setSpecialtiesInternal_f0b18c7e4f_Test {

    private Vet vet;
    private Set<Specialty> specialties;

    @BeforeEach
    public void setUp() {
        vet = new Vet();
        specialties = new HashSet<>();
    }

    @Test
    public void testSetSpecialtiesInternal() {
        Specialty specialty1 = new Specialty();
        specialty1.setName("radiology");
        specialties.add(specialty1);

        Specialty specialty2 = new Specialty();
        specialty2.setName("surgery");
        specialties.add(specialty2);

        vet.setSpecialtiesInternal(specialties);

        assertEquals(specialties, vet.getSpecialtiesInternal());
    }

    @Test
    public void testSetSpecialtiesInternalWithNull() {
        vet.setSpecialtiesInternal(null);
        assertNull(vet.getSpecialtiesInternal());
    }
}
