// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.vet;

import java.util.HashSet;
import java.util.Set;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.samples.petclinic.model.Specialty;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;

public class Vet_getSpecialtiesInternal_ce2cc1ae59_Test {

    private Vet vet;

    @BeforeEach
    public void setup() {
        vet = new Vet();
    }

    @Test
    public void testGetSpecialtiesInternal_WhenSpecialtiesNull() {
        Set<Specialty> specialties = vet.getSpecialtiesInternal();
        assertNotNull(specialties, "Specialties set should not be null");
        assertEquals(0, specialties.size(), "Specialties set should be empty");
    }

    @Test
    public void testGetSpecialtiesInternal_WhenSpecialtiesNotEmpty() {
        Specialty specialty = new Specialty();
        specialty.setName("test");
        vet.getSpecialtiesInternal().add(specialty);

        Set<Specialty> specialties = vet.getSpecialtiesInternal();
        assertNotNull(specialties, "Specialties set should not be null");
        assertEquals(1, specialties.size(), "Specialties set should contain one element");
        assertEquals(specialty, specialties.iterator().next(), "Specialties set should contain the added specialty");
    }
}
