// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.vet;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import org.springframework.beans.support.MutableSortDefinition;
import org.springframework.beans.support.PropertyComparator;
import org.springframework.samples.petclinic.model.Person;
import org.springframework.samples.petclinic.model.Specialty;
import org.springframework.samples.petclinic.model.Vet;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class Vet_getSpecialties_dccc582d89_Test {

    private Vet vet;

    @BeforeEach
    public void setup() {
        vet = new Vet();
    }

    @Test
    public void testGetSpecialtiesWhenEmpty() {
        List<Specialty> specialties = vet.getSpecialties();
        assertTrue(specialties.isEmpty());
    }

    @Test
    public void testGetSpecialtiesWhenNotEmpty() {
        Specialty specialty1 = new Specialty();
        specialty1.setName("Surgery");
        vet.addSpecialty(specialty1);

        Specialty specialty2 = new Specialty();
        specialty2.setName("Dentistry");
        vet.addSpecialty(specialty2);

        List<Specialty> specialties = vet.getSpecialties();
        assertEquals(2, specialties.size());
        assertEquals("Dentistry", specialties.get(0).getName());
        assertEquals("Surgery", specialties.get(1).getName());
    }
}
