// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.vet;

import static org.junit.Assert.assertEquals;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;
import java.util.ArrayList;
import java.util.List;
import org.junit.Test;
import org.springframework.samples.petclinic.model.Specialty;

public class Vet_getSpecialties_dccc582d89_Test {

    @Test
    public void testGetSpecialties() {
        Vet vet = mock(Vet.class);
        List<Specialty> specialties = new ArrayList<>();
        Specialty specialty1 = new Specialty();
        specialty1.setName("specialty1");
        specialties.add(specialty1);
        Specialty specialty2 = new Specialty();
        specialty2.setName("specialty2");
        specialties.add(specialty2);

        when(vet.getSpecialtiesInternal()).thenReturn(specialties);

        List<Specialty> sortedSpecs = vet.getSpecialties();
        assertEquals(2, sortedSpecs.size());
        assertEquals("specialty1", sortedSpecs.get(0).getName());
        assertEquals("specialty2", sortedSpecs.get(1).getName());
    }

    @Test
    public void testGetSpecialtiesEmpty() {
        Vet vet = mock(Vet.class);
        List<Specialty> specialties = new ArrayList<>();

        when(vet.getSpecialtiesInternal()).thenReturn(specialties);

        List<Specialty> sortedSpecs = vet.getSpecialties();
        assertEquals(0, sortedSpecs.size());
    }
}
