// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.vet;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import org.springframework.beans.support.MutableSortDefinition;
import org.springframework.beans.support.PropertyComparator;
import org.springframework.samples.petclinic.model.Person;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.JoinTable;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.Table;
import jakarta.xml.bind.annotation.XmlElement;
import org.springframework.samples.petclinic.vet.Specialty;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class Vet_getSpecialties_dccc582d89_Test {
    private Vet vet;

    @BeforeEach
    public void setup() {
        vet = new Vet();
    }

    @Test
    public void testGetSpecialties() {
        Specialty specialty1 = new Specialty();
        specialty1.setName("specialty1");
        vet.addSpecialty(specialty1);

        Specialty specialty2 = new Specialty();
        specialty2.setName("specialty2");
        vet.addSpecialty(specialty2);

        List<Specialty> specialties = vet.getSpecialties();

        assertEquals(2, specialties.size());
        assertEquals("specialty1", specialties.get(0).getName());
        assertEquals("specialty2", specialties.get(1).getName());
    }

    @Test
    public void testGetSpecialtiesEmpty() {
        List<Specialty> specialties = vet.getSpecialties();
        assertTrue(specialties.isEmpty());
    }
}
