// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.vet;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.samples.petclinic.model.Specialty;
import org.springframework.test.context.junit.jupiter.SpringExtension;

import java.util.Set;

import static org.junit.jupiter.api.Assertions.*;

@ExtendWith(SpringExtension.class)
@SpringBootTest
public class Vet_getSpecialtiesInternal_ce2cc1ae59_Test {

    private Vet vet;

    @BeforeEach
    void setup() {
        vet = new Vet();
    }

    @Test
    public void testGetSpecialtiesInternalWhenSpecialtiesIsNull() {
        Set<Specialty> specialties = vet.getSpecialtiesInternal();
        assertNotNull(specialties);
        assertEquals(0, specialties.size());
    }

    @Test
    public void testGetSpecialtiesInternalWhenSpecialtiesIsNotNull() {
        Specialty specialty = new Specialty();
        specialty.setName("Test Specialty");
        vet.addSpecialty(specialty);

        Set<Specialty> specialties = vet.getSpecialtiesInternal();
        assertNotNull(specialties);
        assertEquals(1, specialties.size());
        assertEquals("Test Specialty", specialties.iterator().next().getName());
    }
}
