// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.vet;

import java.util.Set;
import java.util.HashSet;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import org.springframework.samples.petclinic.model.Specialty;

import static org.junit.jupiter.api.Assertions.*;

public class Vet_setSpecialtiesInternal_f0b18c7e4f_Test {

    private Vet vet;

    @BeforeEach
    public void setup() {
        vet = new Vet();
    }

    @Test
    public void testSetSpecialtiesInternal() {
        Set<Specialty> specialties = new HashSet<>();
        Specialty specialty = new Specialty();
        specialty.setName("Radiology");
        specialties.add(specialty);
        
        vet.setSpecialtiesInternal(specialties);
        
        assertEquals(specialties, vet.getSpecialtiesInternal());
    }
    
    @Test
    public void testSetSpecialtiesInternalEmpty() {
        Set<Specialty> specialties = new HashSet<>();
        
        vet.setSpecialtiesInternal(specialties);
        
        assertEquals(specialties, vet.getSpecialtiesInternal());
    }
}
