// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.vet;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.samples.petclinic.model.Person;
import org.springframework.samples.petclinic.model.Vet;
import org.springframework.samples.petclinic.model.Specialty;

public class Vet_getNrOfSpecialties_85e9551689_Test {

    private Vet vet;

    @BeforeEach
    public void setUp() {
        vet = new Vet();
    }

    @Test
    public void testGetNrOfSpecialties_WhenNoSpecialties() {
        Assertions.assertEquals(0, vet.getNrOfSpecialties());
    }

    @Test
    public void testGetNrOfSpecialties_WhenOneSpecialty() {
        Specialty specialty = new Specialty();
        specialty.setName("surgery");
        vet.addSpecialty(specialty);

        Assertions.assertEquals(1, vet.getNrOfSpecialties());
    }

    @Test
    public void testGetNrOfSpecialties_WhenMultipleSpecialties() {
        Specialty specialty1 = new Specialty();
        specialty1.setName("surgery");
        vet.addSpecialty(specialty1);

        Specialty specialty2 = new Specialty();
        specialty2.setName("dentistry");
        vet.addSpecialty(specialty2);

        Assertions.assertEquals(2, vet.getNrOfSpecialties());
    }
}
