// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.vet;

import java.util.HashSet;
import java.util.Set;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.samples.petclinic.model.Specialty;
import org.springframework.samples.petclinic.model.Vet;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class Vet_getNrOfSpecialties_85e9551689_Test {

    private Vet vet;

    @BeforeEach
    public void setUp() {
        vet = new Vet();
    }

    @Test
    public void testGetNrOfSpecialtiesWithEmptySet() {
        Set<Specialty> specialties = new HashSet<>();
        vet.setSpecialtiesInternal(specialties);
        assertEquals(0, vet.getNrOfSpecialties());
    }

    @Test
    public void testGetNrOfSpecialtiesWithNonEmptySet() {
        Set<Specialty> specialties = new HashSet<>();
        specialties.add(new Specialty());
        specialties.add(new Specialty());
        vet.setSpecialtiesInternal(specialties);
        assertEquals(2, vet.getNrOfSpecialties());
    }
}
