// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.vet;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import org.springframework.beans.support.MutableSortDefinition;
import org.springframework.beans.support.PropertyComparator;
import org.springframework.samples.petclinic.model.Person;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.JoinTable;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.Table;
import jakarta.xml.bind.annotation.XmlElement;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.Mockito;
import org.mockito.MockitoAnnotations;

public class Vet_addSpecialty_76f550ca81_Test {

    @InjectMocks
    Vet vet;

    @Mock
    Specialty specialty;

    @BeforeEach
    public void setup() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testAddSpecialty() {
        vet.addSpecialty(specialty);
        Set<Specialty> specialties = vet.getSpecialtiesInternal();
        Assertions.assertTrue(specialties.contains(specialty));
    }

    @Test
    public void testAddSpecialtyNull() {
        vet.addSpecialty(null);
        Set<Specialty> specialties = vet.getSpecialtiesInternal();
        Assertions.assertFalse(specialties.contains(null));
    }
}
