// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.vet;

import java.util.HashSet;
import java.util.Set;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.samples.petclinic.model.Specialty;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class Vet_setSpecialtiesInternal_f0b18c7e4f_Test {

    private Vet vet;

    @BeforeEach
    public void setUp() {
        vet = new Vet();
    }

    @Test
    public void testSetSpecialtiesInternal_withValidSpecialties() {
        Set<Specialty> specialties = new HashSet<>();
        Specialty specialty1 = new Specialty();
        specialty1.setName("Specialty1");
        specialties.add(specialty1);
        Specialty specialty2 = new Specialty();
        specialty2.setName("Specialty2");
        specialties.add(specialty2);
        
        vet.setSpecialtiesInternal(specialties);
        assertEquals(specialties, vet.getSpecialtiesInternal());
    }

    @Test
    public void testSetSpecialtiesInternal_withEmptySpecialties() {
        Set<Specialty> specialties = new HashSet<>();
        vet.setSpecialtiesInternal(specialties);
        assertEquals(specialties, vet.getSpecialtiesInternal());
    }
}
