// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.vet;

import static org.mockito.Mockito.when;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

@ExtendWith(MockitoExtension.class)
public class VetController_VetController_d8b788bb85_Test {

    @Mock
    private VetRepository vetRepository;

    @InjectMocks
    private VetController vetController;

    @Test
    public void testVetControllerWithValidRepository() {
        // Arrange
        when(vetRepository.findAll()).thenReturn(null); // TODO: Change the return value to a valid list of vets

        // Act
        VetController testVetController = new VetController(vetRepository);

        // Assert
        assertNotNull(testVetController);
    }

    @Test
    public void testVetControllerWithNullRepository() {
        // Arrange
        VetRepository nullRepository = null;

        // Act
        VetController testVetController = new VetController(nullRepository);

        // Assert
        assertNull(testVetController);
    }
}
