// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.vet;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.when;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

public class VetController_VetController_d8b788bb85_Test {

    @InjectMocks
    VetController vetController;

    @Mock
    VetRepository vetRepository;

    @BeforeEach
    public void init() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testVetController() {
        VetRepository clinicServiceMock = org.mockito.Mockito.mock(VetRepository.class);
        VetController vetController = new VetController(clinicServiceMock);

        assertEquals(clinicServiceMock, vetController.getVetRepository());
    }

    @Test
    public void testVetControllerWithNull() {
        VetController vetController = new VetController(null);

        assertEquals(null, vetController.getVetRepository());
    }
}
