// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.vet;

import static org.mockito.Mockito.*;
import static org.junit.Assert.*;

import java.util.Arrays;
import java.util.List;

import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.MockitoJUnitRunner;
import org.springframework.data.domain.Page;
import org.springframework.ui.Model;

@RunWith(MockitoJUnitRunner.class)
public class VetController_addPaginationModel_53c2d9e3be_Test {
	
	@Mock
	private Page<Vet> paginated;

	@Mock
	private Model model;

	@InjectMocks
	private VetController vetController;

	private List<Vet> listVets;
	private String expectedViewName = "vets/vetList";

	@Before
	public void setUp() {
		Vet vet1 = new Vet();
		Vet vet2 = new Vet();
		listVets = Arrays.asList(vet1, vet2);
		when(paginated.getContent()).thenReturn(listVets);
		when(paginated.getTotalPages()).thenReturn(10);
		when(paginated.getTotalElements()).thenReturn((long) listVets.size());
	}

	@Test
	public void testAddPaginationModel() {
		int page = 1;
		String actualViewName = vetController.addPaginationModel(page, paginated, model);
		assertEquals(expectedViewName, actualViewName);
		verify(model).addAttribute("currentPage", page);
		verify(model).addAttribute("totalPages", 10);
		verify(model).addAttribute("totalItems", (long) listVets.size());
		verify(model).addAttribute("listVets", listVets);
	}

	@Test
	public void testAddPaginationModelWithEmptyPage() {
		int page = 0;
		String actualViewName = vetController.addPaginationModel(page, paginated, model);
		assertEquals(expectedViewName, actualViewName);
		verify(model).addAttribute("currentPage", page);
		verify(model).addAttribute("totalPages", 10);
		verify(model).addAttribute("totalItems", (long) listVets.size());
		verify(model).addAttribute("listVets", listVets);
	}
}
