// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.vet;

import static org.mockito.Mockito.when;
import static org.mockito.Mockito.verify;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.ArgumentMatchers.anyInt;
import static org.mockito.ArgumentMatchers.any;

import java.util.Arrays;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageImpl;
import org.springframework.ui.Model;

public class VetController_showVetList_e923f1f5e9_Test {

    @Mock
    private Model model;

    @Mock
    private VetController vetController;

    @Mock
    private Page<Vet> page;

    @BeforeEach
    public void setup() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testShowVetList_DefaultPage() {
        when(vetController.findPaginated(anyInt())).thenReturn(page);
        when(page.toList()).thenReturn(Arrays.asList(new Vet(), new Vet()));
        when(vetController.addPaginationModel(anyInt(), any(Page.class), any(Model.class))).thenReturn("vets/vetList");

        String view = vetController.showVetList(1, model);

        verify(model).addAttribute("vetList", page.toList());
        assertEquals("vets/vetList", view);
    }

    @Test
    public void testShowVetList_SpecificPage() {
        when(vetController.findPaginated(anyInt())).thenReturn(page);
        when(page.toList()).thenReturn(Arrays.asList(new Vet(), new Vet()));
        when(vetController.addPaginationModel(anyInt(), any(Page.class), any(Model.class))).thenReturn("vets/vetList");

        String view = vetController.showVetList(5, model);

        verify(model).addAttribute("vetList", page.toList());
        assertEquals("vets/vetList", view);
    }
}
