// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.vet;

import java.util.Arrays;
import java.util.List;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageImpl;
import org.springframework.data.domain.PageRequest;
import org.springframework.ui.Model;
import org.springframework.ui.ModelMap;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.*;

public class VetController_addPaginationModel_53c2d9e3be_Test {

    private VetController vetController;
    private Model model;

    @BeforeEach
    public void setup() {
        vetController = new VetController();
        model = new ModelMap();
    }

    @Test
    public void testAddPaginationModel_WithValidInput() {
        Vet vet = new Vet();
        List<Vet> vets = Arrays.asList(vet);
        Page<Vet> page = new PageImpl<>(vets, PageRequest.of(0, 1), 1);
        
        String view = vetController.addPaginationModel(1, page, model);
        
        assertEquals("vets/vetList", view);
        assertEquals(1, model.getAttribute("currentPage"));
        assertEquals(1, model.getAttribute("totalPages"));
        assertEquals(1L, model.getAttribute("totalItems"));
        assertEquals(vets, model.getAttribute("listVets"));
    }

    @Test
    public void testAddPaginationModel_WithEmptyPage() {
        Page<Vet> page = new PageImpl<>(Arrays.asList(), PageRequest.of(0, 1), 0);
        
        String view = vetController.addPaginationModel(1, page, model);
        
        assertEquals("vets/vetList", view);
        assertEquals(1, model.getAttribute("currentPage"));
        assertEquals(1, model.getAttribute("totalPages"));
        assertEquals(0L, model.getAttribute("totalItems"));
        assertEquals(Arrays.asList(), model.getAttribute("listVets"));
    }
}
