// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.vet;

import static org.junit.Assert.assertEquals;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

import java.util.Arrays;

import org.junit.Before;
import org.junit.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageImpl;
import org.springframework.ui.Model;

public class VetController_addPaginationModel_53c2d9e3be_Test {

    @InjectMocks
    VetController vetController;

    @Mock
    Page<Vet> paginated;

    @Mock
    Model model;

    @Before
    public void setUp() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testAddPaginationModel() {
        Vet vet = mock(Vet.class);
        when(paginated.getContent()).thenReturn(Arrays.asList(vet, vet));
        when(paginated.getTotalPages()).thenReturn(5);
        when(paginated.getTotalElements()).thenReturn(10L);

        String view = vetController.addPaginationModel(1, paginated, model);

        assertEquals("vets/vetList", view);
    }

    @Test
    public void testAddPaginationModel_EmptyPage() {
        Page<Vet> emptyPage = new PageImpl<>(Arrays.asList());
        String view = vetController.addPaginationModel(1, emptyPage, model);

        assertEquals("vets/vetList", view);
    }
}
