// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.vet;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import org.springframework.ui.Model;
import org.springframework.data.domain.Page;
import java.util.ArrayList;
import java.util.List;
import static org.mockito.Mockito.*;
import static org.junit.jupiter.api.Assertions.*;

class VetController_showVetList_e923f1f5e9_Test {

    @InjectMocks
    VetController vetController;

    @Mock
    Model model;

    @Mock
    Page<Vet> paginated;

    @BeforeEach
    void setUp() {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    void testShowVetList() {
        when(paginated.toList()).thenReturn(new ArrayList<Vet>());
        String result = vetController.showVetList(1, model);
        assertNotNull(result);
    }

    @Test
    void testShowVetListWithMultiplePages() {
        List<Vet> vets = new ArrayList<>();
        vets.add(new Vet());
        vets.add(new Vet());
        when(paginated.toList()).thenReturn(vets);
        String result = vetController.showVetList(2, model);
        assertNotNull(result);
    }

    @Test
    void testShowVetListWithInvalidPage() {
        when(paginated.toList()).thenReturn(new ArrayList<Vet>());
        String result = vetController.showVetList(-1, model);
        assertNotNull(result);
    }
}
