// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.vet;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.samples.petclinic.vet.Vet;
import org.springframework.samples.petclinic.vet.VetRepository;
import org.springframework.samples.petclinic.vet.Vets;

import java.util.Arrays;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.when;

@ExtendWith(MockitoExtension.class)
public class VetController_showResourcesVetList_845ab7f7ca_Test {

    @InjectMocks
    VetController vetController;

    @Mock
    VetRepository vetRepository;

    @Test
    public void testShowResourcesVetList() {
        Vet vet1 = new Vet();
        vet1.setId(1);
        vet1.setFirstName("John");
        vet1.setLastName("Doe");

        Vet vet2 = new Vet();
        vet2.setId(2);
        vet2.setFirstName("Jane");
        vet2.setLastName("Doe");

        List<Vet> vetList = Arrays.asList(vet1, vet2);

        when(vetRepository.findAll()).thenReturn(vetList);

        Vets vets = vetController.showResourcesVetList();

        assertEquals(2, vets.getVetList().size());
        assertEquals(vet1, vets.getVetList().get(0));
        assertEquals(vet2, vets.getVetList().get(1));
    }

    @Test
    public void testShowResourcesVetList_emptyList() {
        when(vetRepository.findAll()).thenReturn(Arrays.asList());

        Vets vets = vetController.showResourcesVetList();

        assertEquals(0, vets.getVetList().size());
    }
}
