// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.vet;

import static org.mockito.Mockito.when;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;

import java.util.Arrays;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

public class VetController_showResourcesVetList_845ab7f7ca_Test {
	
    @InjectMocks
    private VetController vetController;

    @Mock
    private VetRepository vetRepository;

    @BeforeEach
    public void init() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testShowResourcesVetList() {
        Vet vet1 = new Vet();
        vet1.setFirstName("John");
        vet1.setLastName("Doe");

        Vet vet2 = new Vet();
        vet2.setFirstName("Jane");
        vet2.setLastName("Doe");

        when(vetRepository.findAll()).thenReturn(Arrays.asList(vet1, vet2));

        Vets vets = vetController.showResourcesVetList();

        assertNotNull(vets);
        assertNotNull(vets.getVetList());
        assertEquals(2, vets.getVetList().size());
        assertEquals(vet1, vets.getVetList().get(0));
        assertEquals(vet2, vets.getVetList().get(1));
    }

    @Test
    public void testShowResourcesVetListNoVets() {
        when(vetRepository.findAll()).thenReturn(Arrays.asList());

        Vets vets = vetController.showResourcesVetList();

        assertNotNull(vets);
        assertNotNull(vets.getVetList());
        assertEquals(0, vets.getVetList().size());
    }
}
