// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.vet;

import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class Vets_getVetList_f4b55b5394_Test {

    private Vets vets;

    @BeforeEach
    public void setUp() {
        vets = new Vets();
    }

    @Test
    public void testGetVetListWhenVetListIsNull() {
        List<Vet> result = vets.getVetList();
        assertEquals(0, result.size());
    }

    @Test
    public void testGetVetListWhenVetListIsNotNull() {
        List<Vet> vetList = new ArrayList<>();
        Vet vet = new Vet();
        vetList.add(vet);
        vets.setVetList(vetList);

        List<Vet> result = vets.getVetList();
        assertEquals(1, result.size());
        assertEquals(vet, result.get(0));
    }
}
