// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.vet;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;

public class Vets_getVetList_f4b55b5394_Test {

    private Vets vetsUnderTest;
    
    @BeforeEach
    public void setUp() {
        vetsUnderTest = Mockito.mock(Vets.class);
        Mockito.when(vetsUnderTest.getVetList()).thenReturn(new ArrayList<>());
    }

    @Test
    public void testGetVetList_WhenVetsIsNull() {
        List<Vet> result = vetsUnderTest.getVetList();
        assertNotNull(result);
        assertEquals(0, result.size());
    }

    @Test
    public void testGetVetList_WhenVetsIsNotNull() {
        Vet vet = new Vet();
        List<Vet> vetList = new ArrayList<>();
        vetList.add(vet);

        Mockito.when(vetsUnderTest.getVetList()).thenReturn(vetList);

        List<Vet> result = vetsUnderTest.getVetList();
        assertNotNull(result);
        assertEquals(1, result.size());
        assertEquals(vet, result.get(0));
    }
}
