// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.vet;

import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class Vets_getVetList_f4b55b5394_Test {

    private Vets vets;

    @BeforeEach
    void setUp() {
        vets = new Vets();
    }

    @Test
    public void testGetVetListWhenVetsIsNull() {
        assertNull(vets.getVetList());
        List<Vet> vetList = vets.getVetList();
        assertNotNull(vetList);
        assertTrue(vetList.isEmpty());
    }

    @Test
    public void testGetVetListWhenVetsIsNotEmpty() {
        List<Vet> vetList = new ArrayList<>();
        Vet vet = new Vet();
        vet.setFirstName("John");
        vet.setLastName("Doe");
        vetList.add(vet);
        vets.setVetList(vetList);

        List<Vet> retrievedVetList = vets.getVetList();
        assertNotNull(retrievedVetList);
        assertFalse(retrievedVetList.isEmpty());
        assertEquals(vet, retrievedVetList.get(0));
    }
}
