// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import org.junit.jupiter.api.Test;
import org.springframework.samples.petclinic.model.Person;
import org.springframework.util.Assert;

public class Owner_getCity_e8cb16672d_Test {

    @Test
    public void testGetCity() {
        Person person = new Person();
        person.setCity("New York");
        Assert.notNull(person.getCity(), "City should not be null");
        Assert.isTrue(person.getCity().equals("New York"), "City should be New York");
    }

    @Test
    public void testGetCityWithNoCitySet() {
        Person person = new Person();
        Assert.isNull(person.getCity(), "City should be null");
    }
}
