// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import org.junit.jupiter.api.Test;
import org.springframework.validation.BeanPropertyBindingResult;
import org.springframework.web.bind.WebDataBinder;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class OwnerController_setAllowedFields_6961bda542_Test {
    
    @Test
    public void testSetAllowedFields() {
        WebDataBinder dataBinder = new WebDataBinder(new Object());
        OwnerController controller = new OwnerController();
        controller.setAllowedFields(dataBinder);
        
        BeanPropertyBindingResult bindingResult = new BeanPropertyBindingResult(dataBinder.getTarget(), "target");
        dataBinder.validate();
        dataBinder.bind(bindingResult);
        
        assertEquals(1, dataBinder.getDisallowedFields().length);
        assertEquals("id", dataBinder.getDisallowedFields()[0]);
    }

    @Test
    public void testSetAllowedFieldsWithNullObject() {
        WebDataBinder dataBinder = new WebDataBinder(null);
        OwnerController controller = new OwnerController();
        controller.setAllowedFields(dataBinder);
        
        BeanPropertyBindingResult bindingResult = new BeanPropertyBindingResult(dataBinder.getTarget(), "target");
        dataBinder.validate();
        dataBinder.bind(bindingResult);
        
        assertEquals(1, dataBinder.getDisallowedFields().length);
        assertEquals("id", dataBinder.getDisallowedFields()[0]);
    }
}
