// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.WebDataBinder;

import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.verify;

public class OwnerController_setAllowedFields_6961bda542_Test {

    private WebDataBinder dataBinder;

    @BeforeEach
    public void setUp() {
        dataBinder = mock(WebDataBinder.class);
    }

    @Test
    public void testSetAllowedFields() {
        OwnerController controller = new OwnerController();
        controller.setAllowedFields(dataBinder);
        verify(dataBinder).setDisallowedFields("id");
    }

    @Test
    public void testSetAllowedFieldsWithNull() {
        OwnerController controller = new OwnerController();
        controller.setAllowedFields(null);
        verify(dataBinder).setDisallowedFields("id");
    }
}
