// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import java.util.HashMap;
import java.util.Map;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.ui.Model;

public class OwnerController_initCreationForm_d86a3fe6d2_Test {

	private OwnerController ownerController;
	private Map<String, Object> model;
	private String VIEWS_OWNER_CREATE_OR_UPDATE_FORM = "owners/createOrUpdateOwnerForm";

	@BeforeEach
	public void setup() {
		ownerController = new OwnerController();
		model = new HashMap<>();
	}

	@Test
	public void testInitCreationForm() {
		String view = ownerController.initCreationForm(model);
		assertEquals(VIEWS_OWNER_CREATE_OR_UPDATE_FORM, view);
		assertEquals(1, model.size());
		assertEquals(Owner.class, model.get("owner").getClass());
	}

	@Test
	public void testInitCreationFormWithMockModel() {
		Model mockModel = mock(Model.class);
		when(mockModel.addAttribute("owner", new Owner())).thenReturn(mockModel);
		String view = ownerController.initCreationForm(mockModel);
		assertEquals(VIEWS_OWNER_CREATE_OR_UPDATE_FORM, view);
		verify(mockModel).addAttribute("owner", new Owner());
	}
}
