// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.util.Assert;

@SpringBootTest
public class Owner_setAddress_5fc57fbb09_Test {

    private Owner owner;

    @BeforeEach
    public void setup() {
        owner = new Owner();
    }

    @Test
    public void testSetAddress_validAddress() {
        String address = "123 Main St";
        owner.setAddress(address);
        Assert.isTrue(owner.getAddress().equals(address), "Address should be set correctly");
    }

    @Test
    public void testSetAddress_emptyAddress() {
        String address = "";
        owner.setAddress(address);
        Assert.isTrue(owner.getAddress().equals(address), "Empty address should be allowed");
    }

    @Test
    public void testSetAddress_nullAddress() {
        String address = null;
        owner.setAddress(address);
        Assert.isTrue(owner.getAddress() == null, "Null address should be allowed");
    }
}
