// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import org.springframework.validation.BindingResult;
import static org.mockito.Mockito.*;
import static org.junit.jupiter.api.Assertions.*;

class OwnerController_processCreationForm_198f8f2cdf_Test {

    @InjectMocks
    OwnerController ownerController;

    @Mock
    OwnerRepository owners;

    @Mock
    BindingResult result;

    @Mock
    Owner owner;

    @BeforeEach
    void setUp() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    void testProcessCreationForm_success() {
        when(result.hasErrors()).thenReturn(false);
        when(owner.getId()).thenReturn(1);
        assertEquals("redirect:/owners/1", ownerController.processCreationForm(owner, result));
        verify(owners, times(1)).save(owner);
    }

    @Test
    void testProcessCreationForm_failure() {
        when(result.hasErrors()).thenReturn(true);
        assertEquals("owners/createOrUpdateOwnerForm", ownerController.processCreationForm(owner, result));
        verify(owners, never()).save(owner);
    }
}
