// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import org.springframework.samples.petclinic.model.Pet;

public class Owner_getPets_4c451435ac_Test {

    @InjectMocks
    Owner owner;

    @Mock
    List<Pet> pets;

    @BeforeEach
    public void init() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testGetPets() {
        List<Pet> list = new ArrayList<>();
        list.add(new Pet());
        list.add(new Pet());
        owner.setPets(list);

        Assertions.assertEquals(list, owner.getPets());
    }

    @Test
    public void testGetPetsEmpty() {
        List<Pet> list = new ArrayList<>();
        owner.setPets(list);

        Assertions.assertEquals(list, owner.getPets());
    }
}
