// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.*;

import org.springframework.web.bind.WebDataBinder;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

public class OwnerController_setAllowedFields_6961bda542_Test {

    @InjectMocks
    private OwnerController ownerController;

    @Mock
    private WebDataBinder dataBinder;

    @BeforeEach
    public void init() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testSetAllowedFields() {
        ownerController.setAllowedFields(dataBinder);
        verify(dataBinder, times(1)).setDisallowedFields("id");
    }

    @Test
    public void testSetAllowedFieldsWithDifferentField() {
        doThrow(new IllegalArgumentException()).when(dataBinder).setDisallowedFields("name");
        try {
            ownerController.setAllowedFields(dataBinder);
        } catch (IllegalArgumentException e) {
            assertEquals("Disallowed field [name] is invalid", e.getMessage());
        }
    }
}
