// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.samples.petclinic.model.Person;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class Owner_setTelephone_9c88790e49_Test {

    private Person person;

    @BeforeEach
    public void setup() {
        person = new Person();
    }

    @Test
    public void testSetTelephone() {
        String telephone = "1234567890";
        person.setTelephone(telephone);
        assertEquals(telephone, person.getTelephone());
    }

    @Test
    public void testSetTelephoneWithNull() {
        person.setTelephone(null);
        assertEquals(null, person.getTelephone());
    }
}
