// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import org.junit.jupiter.api.Test;
import org.springframework.samples.petclinic.model.Person;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class Owner_getCity_e8cb16672d_Test {

    @Test
    public void testGetCity_ValidCity() {
        Person person = new Person();
        person.setCity("New York");
        assertEquals("New York", person.getCity());
    }

    @Test
    public void testGetCity_EmptyCity() {
        Person person = new Person();
        person.setCity("");
        assertEquals("", person.getCity());
    }
}
