// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.samples.petclinic.model.Pet;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.mockito.Mockito.when;

import java.util.Arrays;

@ExtendWith(MockitoExtension.class)
public class Owner_getPet_ff96e332a1_Test {

    @Mock
    private Pet pet1;

    @Mock
    private Pet pet2;

    @InjectMocks
    private Owner owner;

    @BeforeEach
    void setup() {
        when(pet1.getName()).thenReturn("dog");
        when(pet2.getName()).thenReturn("cat");
        owner.setPetsInternal(Arrays.asList(pet1, pet2));
    }

    @Test
    public void testGetPet_ignoreNew() {
        when(pet1.isNew()).thenReturn(true);
        when(pet2.isNew()).thenReturn(false);
        Pet pet = owner.getPet("dog", true);
        assertNull(pet);

        pet = owner.getPet("cat", true);
        assertEquals(pet2, pet);
    }

    @Test
    public void testGetPet_notIgnoreNew() {
        when(pet1.isNew()).thenReturn(true);
        when(pet2.isNew()).thenReturn(false);
        Pet pet = owner.getPet("dog", false);
        assertEquals(pet1, pet);

        pet = owner.getPet("cat", false);
        assertEquals(pet2, pet);
    }

    @Test
    public void testGetPet_nonExistentPet() {
        Pet pet = owner.getPet("rabbit", true);
        assertNull(pet);

        pet = owner.getPet("rabbit", false);
        assertNull(pet);
    }
}
