// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.when;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import org.springframework.validation.BindingResult;

import jakarta.validation.Valid;

public class OwnerController_processCreationForm_198f8f2cdf_Test {

    @InjectMocks
    OwnerController ownerController;

    @Mock
    OwnerRepository owners;

    @Mock
    BindingResult result;

    @Mock
    Owner owner;

    @BeforeEach
    public void init() {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testProcessCreationForm_Success() {
        when(result.hasErrors()).thenReturn(false);
        when(owner.getId()).thenReturn(1);
        assertEquals("redirect:/owners/1", ownerController.processCreationForm(owner, result));
    }

    @Test
    public void testProcessCreationForm_Failure() {
        when(result.hasErrors()).thenReturn(true);
        assertEquals("owners/createOrUpdateOwnerForm", ownerController.processCreationForm(owner, result));
    }
}
