// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import org.junit.jupiter.api.Test;
import org.springframework.samples.petclinic.model.Person;
import static org.junit.jupiter.api.Assertions.*;

public class Owner_setCity_9dae12ad63_Test {

    @Test
    public void testSetCitySuccess() {
        Person person = new Person();
        String city = "New York";
        person.setCity(city);
        assertEquals(city, person.getCity(), "City should be set correctly");
    }

    @Test
    public void testSetCityFailure() {
        Person person = new Person();
        String city = null;
        assertThrows(NullPointerException.class, () -> {
            person.setCity(city);
        }, "Setting null city should throw NullPointerException");
    }
}
