// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import java.util.ArrayList;
import java.util.List;
import org.springframework.samples.petclinic.model.Person;
import org.springframework.samples.petclinic.model.Pet;
import org.springframework.util.Assert;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
public class Owner_getPet_981a356ffc_Test {

    @InjectMocks
    Owner owner;

    @Mock
    Pet pet;

    @BeforeEach
    void setup() {
        List<Pet> pets = new ArrayList<>();
        pets.add(pet);
        owner.setPetsInternal(pets);
        when(pet.getName()).thenReturn("Fido");
    }

    @Test
    public void testGetPetByName() {
        Pet actualPet = owner.getPet("Fido");
        assertEquals(pet, actualPet, "Expected and actual pets should match.");
    }

    @Test
    public void testGetPetByNameNotFound() {
        Pet actualPet = owner.getPet("Not Fido");
        assertNull(actualPet, "Pet should not be found for incorrect name.");
    }
}
