// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import java.util.HashMap;
import java.util.Map;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class OwnerController_initCreationForm_d86a3fe6d2_Test {
    
    private static final String VIEWS_OWNER_CREATE_OR_UPDATE_FORM = "owners/createOrUpdateOwnerForm";

    private Map<String, Object> model;

    @BeforeEach
    public void setup() {
        model = new HashMap<>();
    }

    @Test
    public void testInitCreationForm() {
        String view = initCreationForm(model);
        assertEquals(VIEWS_OWNER_CREATE_OR_UPDATE_FORM, view);
        assertEquals(new Owner(), model.get("owner"));
    }

    @Test
    public void testInitCreationFormWithExistingOwner() {
        Owner existingOwner = new Owner();
        existingOwner.setFirstName("John");
        existingOwner.setLastName("Doe");
        model.put("owner", existingOwner);

        String view = initCreationForm(model);
        assertEquals(VIEWS_OWNER_CREATE_OR_UPDATE_FORM, view);
        assertEquals(new Owner(), model.get("owner"));
    }

    public String initCreationForm(Map<String, Object> model) {
        Owner owner = new Owner();
        model.put("owner", owner);
        return VIEWS_OWNER_CREATE_OR_UPDATE_FORM;
    }
}
