// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.samples.petclinic.model.Pet;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

public class Owner_getPet_981a356ffc_Test {

    private Owner owner;
    private Pet fido;
    private Pet rex;

    @BeforeEach
    public void setup() {
        owner = new Owner();
        fido = mock(Pet.class);
        rex = mock(Pet.class);

        when(fido.getName()).thenReturn("Fido");
        when(rex.getName()).thenReturn("Rex");

        owner.addPet(fido);
        owner.addPet(rex);
    }

    @Test
    public void testGetPet_success() {
        Pet retrievedPet = owner.getPet("Fido");
        assertEquals(fido, retrievedPet, "Retrieved pet should be Fido.");
    }

    @Test
    public void testGetPet_notFound() {
        Pet retrievedPet = owner.getPet("Buddy");
        assertNull(retrievedPet, "There should be no pet named Buddy.");
    }
}
