// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.when;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import org.springframework.samples.petclinic.owner.OwnerRepository;
import org.springframework.samples.petclinic.owner.Owner;

public class OwnerController_findOwner_66dfd5ad88_Test {

    @InjectMocks
    private OwnerController ownerController;

    @Mock
    private OwnerRepository owners;

    @BeforeEach
    public void init() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testFindOwnerWithNullId() {
        Owner owner = ownerController.findOwner(null);
        assertEquals(new Owner(), owner);
    }

    @Test
    public void testFindOwnerWithValidId() {
        Owner expectedOwner = new Owner();
        expectedOwner.setFirstName("John");
        expectedOwner.setLastName("Doe");

        when(owners.findById(1)).thenReturn(expectedOwner);

        Owner actualOwner = ownerController.findOwner(1);
        assertEquals(expectedOwner, actualOwner);
    }

    @Test
    public void testFindOwnerWithInvalidId() {
        when(owners.findById(2)).thenReturn(null);

        Owner actualOwner = ownerController.findOwner(2);
        assertEquals(null, actualOwner);
    }
}
