// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.data.domain.Page;
import org.springframework.ui.Model;

public class OwnerController_addPaginationModel_996bca2e5f_Test {
    private Model model;
    private Page<Owner> paginated;
    private OwnerController ownerController;

    @BeforeEach
    public void setUp() {
        model = mock(Model.class);
        paginated = mock(Page.class);
        ownerController = new OwnerController();
    }

    @Test
    public void testAddPaginationModel_success() {
        int page = 1;
        List<Owner> listOwners = Arrays.asList(new Owner(), new Owner());
        when(paginated.getContent()).thenReturn(listOwners);
        when(paginated.getTotalPages()).thenReturn(5);
        when(paginated.getTotalElements()).thenReturn(10L);

        String result = ownerController.addPaginationModel(page, model, paginated);
        assertEquals("owners/ownersList", result);
    }

    @Test
    public void testAddPaginationModel_emptyList() {
        int page = 1;
        List<Owner> listOwners = Arrays.asList();
        when(paginated.getContent()).thenReturn(listOwners);
        when(paginated.getTotalPages()).thenReturn(0);
        when(paginated.getTotalElements()).thenReturn(0L);

        String result = ownerController.addPaginationModel(page, model, paginated);
        assertEquals("owners/ownersList", result);
    }
}
