// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import org.junit.jupiter.api.Test;
import org.springframework.samples.petclinic.model.Person;
import org.springframework.util.Assert;

public class Owner_getAddress_4a6790754a_Test {
    
    @Test
    public void testGetAddress() {
        Person person = new Person();
        person.setAddress("123 Main St");
        Assert.notNull(person.getAddress(), "Address should not be null");
        Assert.isTrue(person.getAddress().equals("123 Main St"), "Address should be '123 Main St'");
    }
    
    @Test
    public void testGetAddress_Null() {
        Person person = new Person();
        person.setAddress(null);
        Assert.isNull(person.getAddress(), "Address should be null");
    }
}
