// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.MockitoAnnotations;
import org.springframework.samples.petclinic.model.Pet;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class Owner_addPet_b33ed0f86c_Test {

    @InjectMocks
    private Owner owner;

    @BeforeEach
    public void setUp() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testAddPetSuccess() {
        Pet pet = new Pet();
        pet.setName("Max");
        owner.addPet(pet);
        assertEquals(1, owner.getPets().size());
        assertEquals("Max", owner.getPets().get(0).getName());
    }

    @Test
    public void testAddPetFailure() {
        Pet pet = new Pet();
        pet.setName("Max");
        pet.setId(1);
        owner.addPet(pet);
        assertEquals(0, owner.getPets().size());
    }
}
