// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.samples.petclinic.model.Person;
import org.springframework.util.Assert;

public class Owner_getTelephone_a676fabad4_Test
{
    private Person owner;

    @BeforeEach
    public void setup(){
        owner = new Person();
    }

    @Test
    public void testGetTelephoneWhenTelephoneIsSet(){
        String expectedTelephone = "1234567890";
        owner.setTelephone(expectedTelephone);
        String actualTelephone = owner.getTelephone();
        Assert.isTrue(expectedTelephone.equals(actualTelephone), "Telephone should be equal to set value");
    }

    @Test
    public void testGetTelephoneWhenTelephoneIsNotSet(){
        String expectedTelephone = null;
        String actualTelephone = owner.getTelephone();
        Assert.isTrue(expectedTelephone == actualTelephone, "Telephone should be null when not set");
    }
}
