// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.samples.petclinic.model.Person;

public class Owner_getTelephone_a676fabad4_Test {

    private Person person;

    @BeforeEach
    public void setUp() {
        person = new Person();
    }

    @Test
    public void testGetTelephone_ValidNumber() {
        String validNumber = "1234567890";
        person.setTelephone(validNumber);
        String result = person.getTelephone();
        Assertions.assertEquals(validNumber, result, "Telephone number should match the valid number set");
    }

    @Test
    public void testGetTelephone_EmptyString() {
        String emptyNumber = "";
        person.setTelephone(emptyNumber);
        String result = person.getTelephone();
        Assertions.assertEquals(emptyNumber, result, "Telephone number should match the empty string set");
    }
    
    @Test
    public void testGetTelephone_Null() {
        person.setTelephone(null);
        String result = person.getTelephone();
        Assertions.assertNull(result, "Telephone number should be null");
    }
}
