// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import org.junit.jupiter.api.Test;
import org.springframework.samples.petclinic.model.Person;
import org.springframework.util.Assert;

public class Owner_setTelephone_9c88790e49_Test {
    
    @Test
    public void testSetTelephone() {
        Person owner = new Person();
        String telephone = "1234567890";
        owner.setTelephone(telephone);
        Assert.isTrue(owner.getTelephone().equals(telephone), "Telephone numbers do not match");
    }

    @Test
    public void testSetTelephoneFailure() {
        Person owner = new Person();
        String telephone = null;
        try {
            owner.setTelephone(telephone);
        } catch (IllegalArgumentException e) {
            Assert.isTrue(e.getMessage().contains("Telephone number must not be null"), 
                "Expected exception message to contain 'Telephone number must not be null'");
        }
    }

    @Test
    public void testSetTelephoneEdgeCase() {
        Person owner = new Person();
        String telephone = "";
        owner.setTelephone(telephone);
        Assert.isTrue(owner.getTelephone().equals(telephone), "Telephone numbers do not match");
    }
}
