// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.samples.petclinic.model.Person;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class Owner_getAddress_4a6790754a_Test {

    private Person person;

    @BeforeEach
    public void setUp() {
        person = new Person();
    }

    @Test
    public void testGetAddress() {
        String expectedAddress = "123 Main St";
        person.setAddress(expectedAddress);
        String actualAddress = person.getAddress();
        assertEquals(expectedAddress, actualAddress, "Address should match");
    }

    @Test
    public void testGetAddressWhenAddressIsNull() {
        String expectedAddress = null;
        person.setAddress(expectedAddress);
        String actualAddress = person.getAddress();
        assertEquals(expectedAddress, actualAddress, "Address should be null");
    }
}
