// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.util.HashMap;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;

@ExtendWith(MockitoExtension.class)
public class OwnerController_initCreationForm_d86a3fe6d2_Test {

    @InjectMocks
    private OwnerController ownerController;

    @Mock
    private Map<String, Object> model;

    @Test
    public void initCreationForm_success() {
        model = new HashMap<>();
        String viewName = ownerController.initCreationForm(model);

        assertEquals("owners/createOrUpdateOwnerForm", viewName);
        assertNotNull(model.get("owner"));
        assertEquals(Owner.class, model.get("owner").getClass());
    }

    @Test
    public void initCreationForm_modelIsNull() {
        String viewName = ownerController.initCreationForm(null);

        assertEquals("owners/createOrUpdateOwnerForm", viewName);
    }
}
