// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.when;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.samples.petclinic.model.Owner;
import org.springframework.samples.petclinic.service.ClinicService;

@ExtendWith(MockitoExtension.class)
public class OwnerController_findOwner_66dfd5ad88_Test {

    @InjectMocks
    private OwnerController ownerController;

    @Mock
    private ClinicService clinicService;

    private Owner owner;

    @BeforeEach
    public void setup() {
        owner = new Owner();
        owner.setId(1);
    }

    @Test
    public void testFindOwnerWithId() {
        when(clinicService.findOwnerById(1)).thenReturn(owner);
        Owner result = ownerController.findOwner(1);
        assertEquals(owner, result);
    }

    @Test
    public void testFindOwnerWithoutId() {
        Owner result = ownerController.findOwner(null);
        assertEquals(new Owner(), result);
    }
}
