// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.Mockito;
import org.springframework.validation.BindingResult;

import jakarta.validation.Valid;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.when;

public class OwnerController_processCreationForm_198f8f2cdf_Test {

    private OwnerController ownerController;

    @Mock
    private Owners owners;

    @Mock
    private BindingResult result;

    @BeforeEach
    public void setup() {
        ownerController = new OwnerController(owners);
    }

    @Test
    public void testProcessCreationForm_success() {
        Owner owner = new Owner();
        owner.setId(1);
        when(result.hasErrors()).thenReturn(false);
        when(owners.save(Mockito.any(Owner.class))).thenReturn(owner);
        String view = ownerController.processCreationForm(owner, result);
        assertEquals("redirect:/owners/1", view);
    }

    @Test
    public void testProcessCreationForm_failure() {
        Owner owner = new Owner();
        when(result.hasErrors()).thenReturn(true);
        String view = ownerController.processCreationForm(owner, result);
        assertEquals("VIEWS_OWNER_CREATE_OR_UPDATE_FORM", view);
    }
}
