// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import static org.junit.jupiter.api.Assertions.assertEquals;

import java.util.ArrayList;
import java.util.List;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.samples.petclinic.model.Person;
import org.springframework.samples.petclinic.model.Pet;

public class Owner_getPets_4c451435ac_Test {

  private Person person;

  @BeforeEach
  public void setup() {
    person = new Person();
    Pet pet1 = new Pet();
    pet1.setName("Buddy");
    Pet pet2 = new Pet();
    pet2.setName("Milo");
    List<Pet> pets = new ArrayList<>();
    pets.add(pet1);
    pets.add(pet2);
    person.setPets(pets);
  }

  @Test
  public void testGetPets() {
    List<Pet> pets = person.getPets();
    assertEquals(2, pets.size());
    assertEquals("Buddy", pets.get(0).getName());
    assertEquals("Milo", pets.get(1).getName());
  }

  @Test
  public void testGetPets_noPets() {
    Person person = new Person();
    List<Pet> pets = person.getPets();
    assertEquals(0, pets.size());
  }
}
