// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.samples.petclinic.model.Pet;

import java.util.ArrayList;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;

public class Owner_getPet_f9297dd0a1_Test {

    private Owner owner;
    private Pet pet1;
    private Pet pet2;

    @BeforeEach
    public void setup() {
        owner = new Owner();
        pet1 = new Pet();
        pet1.setId(1);
        pet1.setName("Rex");
        pet2 = new Pet();
        pet2.setId(2);
        pet2.setName("Fido");

        List<Pet> pets = new ArrayList<>();
        pets.add(pet1);
        pets.add(pet2);

        owner.setPets(pets);
    }

    @Test
    public void testGetPetWithExistingId() {
        Pet pet = owner.getPet(1);
        assertEquals(pet1, pet);
    }

    @Test
    public void testGetPetWithNonExistingId() {
        Pet pet = owner.getPet(3);
        assertNull(pet);
    }
}
