// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import static org.mockito.Mockito.when;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;

@ExtendWith(MockitoExtension.class)
public class OwnerController_findOwner_66dfd5ad88_Test {

    @Mock
    private OwnerRepository owners;

    @InjectMocks
    private OwnerController ownerController;

    @Test
    void testFindOwnerWithNullId() {
        Owner owner = ownerController.findOwner(null);
        assertNotNull(owner, "Owner should not be null");
    }

    @Test
    void testFindOwnerWithId() {
        Integer ownerId = 1;
        Owner expectedOwner = new Owner();

        when(owners.findById(ownerId)).thenReturn(expectedOwner);

        Owner actualOwner = ownerController.findOwner(ownerId);
        assertNotNull(actualOwner, "Owner should not be null");
    }

    @Test
    void testFindOwnerWithNonExistentId() {
        Integer ownerId = 2;

        when(owners.findById(ownerId)).thenReturn(null);

        Owner actualOwner = ownerController.findOwner(ownerId);
        assertNull(actualOwner, "Owner should be null");
    }
}
