// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import java.util.ArrayList;
import java.util.List;
import org.springframework.samples.petclinic.model.Person;
import org.springframework.samples.petclinic.owner.Pet;
import org.springframework.util.Assert;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class Owner_addPet_b33ed0f86c_Test {
    private Person owner;

    @BeforeEach
    void setup() {
        owner = new Person();
    }

    @Test
    void testAddPet_newPet() {
        Pet pet = new Pet();
        // TODO: Set pet properties as needed
        pet.setName("Fluffy");
        owner.addPet(pet);

        assertTrue(owner.getPets().contains(pet), "Failed to add new pet");
    }

    @Test
    void testAddPet_existingPet() {
        Pet pet = new Pet();
        // TODO: Set pet properties as needed
        pet.setName("Fluffy");
        pet.setId(1);
        owner.addPet(pet);

        assertFalse(owner.getPets().contains(pet), "Added an existing pet");
    }
}
