// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import org.junit.jupiter.api.Test;
import org.springframework.samples.petclinic.model.Person;
import org.springframework.util.Assert;

public class Owner_toString_ceffa8036e_Test {

    @Test
    public void testToString() {
        Person person = new Person();
        person.setFirstName("John");
        person.setLastName("Doe");
        Owner owner = new Owner();
        owner.setPerson(person);
        owner.setAddress("123 Main St");
        owner.setCity("Springfield");
        owner.setTelephone("555-555-5555");

        String expectedOutput = "Owner@12345678[id=0, new=true, lastName='Doe', firstName='John', address='123 Main St', city='Springfield', telephone='555-555-5555']";
        String actualOutput = owner.toString();

        Assert.isTrue(expectedOutput.equals(actualOutput), "Expected and actual output of toString method do not match");
    }

    @Test
    public void testToString_NullValues() {
        Person person = new Person();
        Owner owner = new Owner();
        owner.setPerson(person);

        String expectedOutput = "Owner@12345678[id=0, new=true, lastName=null, firstName=null, address=null, city=null, telephone=null]";
        String actualOutput = owner.toString();

        Assert.isTrue(expectedOutput.equals(actualOutput), "Expected and actual output of toString method do not match when values are null");
    }
}
