// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.samples.petclinic.model.Person;
import static org.junit.jupiter.api.Assertions.assertEquals;

class Owner_getTelephone_a676fabad4_Test {

    private Person person;

    @BeforeEach
    void setUp() {
        person = new Person();
    }

    @Test
    public void testGetTelephone() {
        // TODO: Replace with the actual phone number
        String expected = "1234567890";
        person.setTelephone(expected);
        String actual = person.getTelephone();
        assertEquals(expected, actual);
    }

    @Test
    public void testGetTelephoneWithEmptyString() {
        String expected = "";
        person.setTelephone(expected);
        String actual = person.getTelephone();
        assertEquals(expected, actual);
    }
}
