// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.samples.petclinic.model.Person;

public class Owner_setCity_9dae12ad63_Test {

    private Person person;

    @BeforeEach
    public void setup() {
        person = new Person();
    }

    @Test
    public void testSetCity_ValidCity() {
        String validCity = "New York";
        person.setCity(validCity);
        Assertions.assertEquals(validCity, person.getCity(), "The city should be set correctly when a valid city is provided.");
    }

    @Test
    public void testSetCity_NullCity() {
        String nullCity = null;
        person.setCity(nullCity);
        Assertions.assertNull(person.getCity(), "The city should be null when a null city is provided.");
    }

    @Test
    public void testSetCity_EmptyCity() {
        String emptyCity = "";
        person.setCity(emptyCity);
        Assertions.assertEquals(emptyCity, person.getCity(), "The city should be empty when an empty city is provided.");
    }
}
