// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.mockito.Mockito.verify;

public class OwnerController_OwnerController_8b45ad788c_Test {

    @Mock
    private OwnerRepository ownerRepository;

    private OwnerController ownerController;

    @BeforeEach
    public void setup() {
        MockitoAnnotations.initMocks(this);
        this.ownerController = new OwnerController(ownerRepository);
    }

    @Test
    public void testOwnerControllerConstructor() {
        assertNotNull(ownerController);
        verify(ownerRepository).findAll();
    }

    @Test
    public void testOwnerControllerConstructor_NullOwnerRepository() {
        try {
            new OwnerController(null);
        } catch (IllegalArgumentException e) {
            assertEquals("OwnerRepository must not be null!", e.getMessage());
        }
    }
}
