// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.samples.petclinic.model.Person;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class Owner_setCity_9dae12ad63_Test {

    private Person person;

    @BeforeEach
    public void setUp() {
        person = new Person();
    }

    @Test
    public void testSetCity_Success() {
        String city = "New York";
        person.setCity(city);
        assertEquals(city, person.getCity(), "City should be set successfully");
    }

    @Test
    public void testSetCity_Null() {
        String city = null;
        person.setCity(city);
        assertEquals(city, person.getCity(), "City should be set as null");
    }
}
