// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import org.springframework.samples.petclinic.model.Person;
import org.springframework.samples.petclinic.owner.Pet;
import org.springframework.samples.petclinic.owner.Owner;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class Owner_getPets_4c451435ac_Test {

    private Owner owner;
    private Pet pet1;
    private Pet pet2;

    @BeforeEach
    public void setup() {
        owner = new Owner();
        pet1 = Mockito.mock(Pet.class);
        pet2 = Mockito.mock(Pet.class);
        List<Pet> pets = new ArrayList<>();
        pets.add(pet1);
        pets.add(pet2);
        owner.setPets(pets);
    }

    @Test
    public void testGetPets() {
        List<Pet> pets = owner.getPets();
        assertEquals(2, pets.size());
        assertEquals(pet1, pets.get(0));
        assertEquals(pet2, pets.get(1));
    }

    @Test
    public void testGetPetsEmpty() {
        owner.setPets(new ArrayList<>());
        List<Pet> pets = owner.getPets();
        assertEquals(0, pets.size());
    }
}
