// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import org.springframework.validation.BindingResult;
import static org.mockito.Mockito.*;
import static org.assertj.core.api.Assertions.*;

public class OwnerController_processUpdateOwnerForm_a228651f5b_Test {

    @Mock
    private OwnerRepository owners;
    
    @Mock
    private BindingResult result;
    
    private Owner owner;
    
    private OwnerController controller;

    @BeforeEach
    public void setup() {
        MockitoAnnotations.initMocks(this);
        controller = new OwnerController(owners);
        owner = new Owner();
    }

    @Test
    public void testProcessUpdateOwnerForm_hasErrors() {
        when(result.hasErrors()).thenReturn(true);

        String view = controller.processUpdateOwnerForm(owner, result, 1);
        
        assertThat(view).isEqualTo("owners/createOrUpdateOwnerForm");
        verify(owners, times(0)).save(any(Owner.class));
    }

    @Test
    public void testProcessUpdateOwnerForm_noErrors() {
        when(result.hasErrors()).thenReturn(false);

        String view = controller.processUpdateOwnerForm(owner, result, 1);
        
        assertThat(view).isEqualTo("redirect:/owners/1");
        verify(owners, times(1)).save(any(Owner.class));
    }
}
