// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.samples.petclinic.model.Person;

public class Owner_getAddress_4a6790754a_Test {

    private Person person;

    @BeforeEach
    public void setUp() {
        person = new Person();
    }

    @Test
    public void testGetAddressWhenAddressIsSet() {
        String expectedAddress = "123 Main Street";
        person.setAddress(expectedAddress);
        String actualAddress = person.getAddress();
        Assertions.assertEquals(expectedAddress, actualAddress, "Expected address did not match actual address");
    }

    @Test
    public void testGetAddressWhenAddressIsNotSet() {
        String actualAddress = person.getAddress();
        Assertions.assertNull(actualAddress, "Address should be null when not set");
    }

}
