// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import org.junit.jupiter.api.Test;
import org.springframework.samples.petclinic.model.Person;
import org.springframework.util.Assert;

public class Owner_getCity_e8cb16672d_Test {

    @Test
    public void testGetCityWhenCityIsNotNull() {
        Person person = new Person();
        person.setCity("New York");
        String city = person.getCity();
        Assert.notNull(city, "City should not be null");
        Assert.isTrue(city.equals("New York"), "Expected city to be 'New York'");
    }

    @Test
    public void testGetCityWhenCityIsNull() {
        Person person = new Person();
        person.setCity(null);
        String city = person.getCity();
        Assert.isNull(city, "City should be null");
    }
}
