// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.when;

import java.util.Collections;
import java.util.Optional;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

public class OwnerController_OwnerController_8b45ad788c_Test {

    @Mock
    private OwnerRepository ownerRepository;

    @InjectMocks
    private OwnerController ownerController;

    @BeforeEach
    public void init() {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testOwnerController() {
        Owner owner = new Owner();
        owner.setId(1);
        when(ownerRepository.findById(1)).thenReturn(Optional.of(owner));
        
        Owner result = ownerController.showOwner(1);
        assertEquals(owner, result);
    }

    @Test
    public void testOwnerController_NoOwner() {
        when(ownerRepository.findById(1)).thenReturn(Optional.empty());

        Owner result = ownerController.showOwner(1);
        assertEquals(null, result);
    }
}
