// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit.jupiter.SpringExtension;
import static org.junit.jupiter.api.Assertions.assertEquals;

@ExtendWith(SpringExtension.class)
@SpringBootTest
public class OwnerController_initFindForm_d49390f8bd_Test {

    @InjectMocks
    OwnerController ownerController;

    @Test
    public void testInitFindForm() {
        String viewName = ownerController.initFindForm();
        assertEquals("owners/findOwners", viewName);
    }

    @Test
    public void testInitFindFormFailure() {
        String viewName = ownerController.initFindForm();
        assertEquals("owners/findOwner", viewName); // This will fail because the actual return value is "owners/findOwners"
    }
}
