// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

import java.util.Arrays;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.samples.petclinic.model.Pet;

public class Owner_getPet_ff96e332a1_Test {
    private Owner owner;
    private Pet pet1;
    private Pet pet2;

    @BeforeEach
    public void setup() {
        owner = new Owner();
        pet1 = mock(Pet.class);
        pet2 = mock(Pet.class);
        
        when(pet1.getName()).thenReturn("Fido");
        when(pet1.isNew()).thenReturn(false);
        
        when(pet2.getName()).thenReturn("Buddy");
        when(pet2.isNew()).thenReturn(true);
        
        owner.setPetsInternal(Arrays.asList(pet1, pet2));
    }

    @Test
    public void testGetPet() {
        Pet pet = owner.getPet("Fido", false);
        assertEquals(pet1, pet);
    }

    @Test
    public void testGetPetIgnoreNew() {
        Pet pet = owner.getPet("Buddy", true);
        assertNull(pet);
    }

    @Test
    public void testGetPetNonExistent() {
        Pet pet = owner.getPet("NonExistent", false);
        assertNull(pet);
    }
}
