// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.samples.petclinic.model.Person;
import org.springframework.test.context.junit4.SpringRunner;
import static org.junit.Assert.*;

@RunWith(SpringRunner.class)
@SpringBootTest
public class Owner_setAddress_5fc57fbb09_Test {

    @Test
    public void testSetAddress() {
        Person owner = new Person();
        String expectedAddress = "123 Main Street";
        owner.setAddress(expectedAddress);
        assertEquals(expectedAddress, owner.getAddress());
    }

    @Test
    public void testSetAddress_Null() {
        Person owner = new Person();
        String expectedAddress = null;
        owner.setAddress(expectedAddress);
        assertNull(owner.getAddress());
    }

}
