// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.springframework.samples.petclinic.model.Person;

public class Owner_setTelephone_9c88790e49_Test {

    @Test
    public void testSetTelephoneWithValidInput() {
        Person person = new Person();
        String telephone = "1234567890";
        person.setTelephone(telephone);
        Assertions.assertEquals(telephone, person.getTelephone());
    }

    @Test
    public void testSetTelephoneWithNullInput() {
        Person person = new Person();
        String telephone = null;
        person.setTelephone(telephone);
        Assertions.assertNull(person.getTelephone());
    }
}
