// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import org.springframework.samples.petclinic.model.Pet;
import java.util.Arrays;
import java.util.List;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;

public class Owner_getPet_f9297dd0a1_Test {

    private Owner owner;
    private Pet pet1, pet2;

    @BeforeEach
    void setup() {
        owner = new Owner();
        pet1 = Mockito.mock(Pet.class);
        pet2 = Mockito.mock(Pet.class);

        Mockito.when(pet1.isNew()).thenReturn(false);
        Mockito.when(pet2.isNew()).thenReturn(false);
        Mockito.when(pet1.getId()).thenReturn(1);
        Mockito.when(pet2.getId()).thenReturn(2);

        List<Pet> petList = Arrays.asList(pet1, pet2);
        owner.setPetsInternal(petList);
    }

    @Test
    void testGetPetValidId() {
        Pet result = owner.getPet(1);
        assertEquals(pet1, result);
    }

    @Test
    void testGetPetInvalidId() {
        Pet result = owner.getPet(3);
        assertNull(result);
    }
}
