// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.ui.Model;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

@ExtendWith(MockitoExtension.class)
public class OwnerController_initUpdateOwnerForm_5166028c6b_Test {

    @Mock
    private OwnerRepository owners;

    @Mock
    private Model model;

    @InjectMocks
    private OwnerController controller;

    @Test
    public void testInitUpdateOwnerForm() {
        Owner owner = new Owner();
        owner.setId(1);
        when(owners.findById(1)).thenReturn(owner);

        String view = controller.initUpdateOwnerForm(1, model);

        verify(model).addAttribute(owner);
        assertEquals("owners/createOrUpdateOwnerForm", view);
    }

    @Test
    public void testInitUpdateOwnerFormWithNonExistentOwner() {
        when(owners.findById(1)).thenReturn(null);

        String view = controller.initUpdateOwnerForm(1, model);

        // TODO: Here, you should assert that an appropriate error message is added to the model
        // This will depend on how your application is designed to handle this case
        assertEquals("owners/createOrUpdateOwnerForm", view);
    }
}
