// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.junit.jupiter.MockitoExtension;
import static org.junit.jupiter.api.Assertions.assertEquals;

@ExtendWith(MockitoExtension.class)
public class OwnerController_initFindForm_d49390f8bd_Test {

    @InjectMocks
    OwnerController ownerController;

    @Test
    public void testInitFindForm_success() {
        String viewName = ownerController.initFindForm();
        assertEquals("owners/findOwners", viewName);
    }

    @Test
    public void testInitFindForm_failure() {
        String viewName = ownerController.initFindForm();
        assertEquals("owners/findOwner", viewName);
    }
}
