// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import java.time.LocalDate;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.samples.petclinic.owner.Pet;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class Pet_getBirthDate_7f1e9ebfb7_Test {

	private Pet pet;

	@BeforeEach
	public void setup() {
		pet = new Pet();
	}

	@Test
	public void testGetBirthDateWithValidDate() {
		LocalDate expectedDate = LocalDate.of(2020, 1, 1);
		pet.setBirthDate(expectedDate);
		
		LocalDate actualDate = pet.getBirthDate();
		
		assertEquals(expectedDate, actualDate, "The expected birth date does not match the actual birth date");
	}

	@Test
	public void testGetBirthDateWithNullDate() {
		pet.setBirthDate(null);
		
		LocalDate actualDate = pet.getBirthDate();
		
		assertEquals(null, actualDate, "The expected birth date does not match the actual birth date");
	}
}
