// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import java.time.LocalDate;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class Pet_setBirthDate_bee672f49b_Test {

    private Pet pet;

    @BeforeEach
    public void setup() {
        pet = new Pet();
    }

    @Test
    public void testSetBirthDate() {
        LocalDate birthDate = LocalDate.of(2022, 1, 1);
        pet.setBirthDate(birthDate);
        assertEquals(birthDate, pet.getBirthDate(), "Birth date should be set correctly");
    }

    @Test
    public void testSetBirthDateNull() {
        pet.setBirthDate(null);
        assertEquals(null, pet.getBirthDate(), "Birth date should be null");
    }
}
