// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.samples.petclinic.model.PetType;

class Pet_setType_9a8aa62bfe_Test {

    private Pet pet;

    @BeforeEach
    void setup() {
        pet = new Pet();
    }

    @Test
    void testSetType() {
        PetType type = new PetType();
        type.setName("Dog");
        pet.setType(type);

        Assertions.assertEquals("Dog", pet.getType().getName(), "Expected pet type to be 'Dog'");
    }

    @Test
    void testSetType_Null() {
        pet.setType(null);

        Assertions.assertNull(pet.getType(), "Expected pet type to be null");
    }
}
