// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import java.time.LocalDate;

public class Pet_getBirthDate_7f1e9ebfb7_Test {

    @Test
    public void testGetBirthDate() {
        Pet pet = new Pet();
        LocalDate birthDate = LocalDate.of(2020, 1, 1);
        pet.setBirthDate(birthDate);

        LocalDate actualBirthDate = pet.getBirthDate();

        Assertions.assertEquals(birthDate, actualBirthDate, "The expected birth date does not match the actual birth date");
    }

    @Test
    public void testGetBirthDateNull() {
        Pet pet = new Pet();

        LocalDate actualBirthDate = pet.getBirthDate();

        Assertions.assertNull(actualBirthDate, "The birth date is not null");
    }
}
