// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import org.springframework.samples.petclinic.owner.Visit;
import org.springframework.samples.petclinic.owner.Pet;

import java.util.HashSet;
import java.util.Set;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

public class Pet_addVisit_f1d5eb0dda_Test {

    private Pet pet;

    @BeforeEach
    public void setUp() {
        pet = new Pet();
    }

    @Test
    public void testAddVisit() {
        Visit visit = Mockito.mock(Visit.class);
        pet.addVisit(visit);
        assertEquals(1, pet.getVisits().size());
    }

    @Test
    public void testAddVisit_NullVisit() {
        assertThrows(NullPointerException.class, () -> pet.addVisit(null));
    }

    @Test
    public void testAddVisit_MultipleVisits() {
        Set<Visit> visits = new HashSet<>();
        for (int i = 0; i < 5; i++) {
            Visit visit = Mockito.mock(Visit.class);
            visits.add(visit);
            pet.addVisit(visit);
        }
        assertEquals(visits.size(), pet.getVisits().size());
    }
}
