// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.samples.petclinic.owner.Pet;
import org.springframework.samples.petclinic.owner.PetType;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;

public class Pet_getType_3e60e43fbc_Test {

    private Pet pet;

    @BeforeEach
    public void setup() {
        pet = new Pet();
    }

    @Test
    public void testGetTypeWhenTypeIsSet() {
        PetType type = new PetType();
        type.setName("Dog");
        pet.setType(type);

        PetType actualType = pet.getType();

        assertEquals(type, actualType, "Expected and actual PetType should be the same");
    }

    @Test
    public void testGetTypeWhenTypeIsNotSet() {
        PetType actualType = pet.getType();

        assertNull(actualType, "PetType should be null when it's not set");
    }
}
