// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.samples.petclinic.model.Pet;
import org.springframework.samples.petclinic.model.PetType;

public class Pet_getType_3e60e43fbc_Test {

    private Pet pet;

    @BeforeEach
    public void setup() {
        pet = new Pet();
    }

    @Test
    public void testGetTypeWhenTypeIsSet() {
        PetType expectedType = new PetType();
        expectedType.setName("Dog");
        pet.setType(expectedType);

        PetType actualType = pet.getType();

        Assertions.assertNotNull(actualType, "The actual type should not be null");
        Assertions.assertEquals(expectedType, actualType, "The actual type doesn't match the expected type");
    }

    @Test
    public void testGetTypeWhenTypeIsNotSet() {
        PetType actualType = pet.getType();
        Assertions.assertNull(actualType, "The actual type should be null as it was not set");
    }
}
