// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.samples.petclinic.model.PetType;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class Pet_setType_9a8aa62bfe_Test {

    private Pet petUnderTest;

    @BeforeEach
    public void setUp() {
        petUnderTest = new Pet();
    }

    @Test
    public void testSetType() {
        // TODO: Change the value to a valid PetType
        PetType type = new PetType();
        type.setName("Dog");

        petUnderTest.setType(type);
        assertEquals(type, petUnderTest.getType());
    }

    @Test
    public void testSetType_null() {
        petUnderTest.setType(null);
        assertEquals(null, petUnderTest.getType());
    }
}
