// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.when;
import static org.mockito.Mockito.mock;

import java.util.Arrays;
import java.util.Collection;
import java.util.LinkedHashSet;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.samples.petclinic.visit.Visit;

public class Pet_getVisits_e2a563d9d4_Test {

    private Pet pet;

    @BeforeEach
    public void setup() {
        pet = new Pet();
    }

    @Test
    public void testGetVisits_NoVisits() {
        Collection<Visit> visits = pet.getVisits();
        assertEquals(0, visits.size(), "Should be no visits");
    }

    @Test
    public void testGetVisits_WithVisits() {
        Visit visit1 = mock(Visit.class);
        Visit visit2 = mock(Visit.class);

        Set<Visit> visitSet = new LinkedHashSet<>(Arrays.asList(visit1, visit2));
        pet.setVisitsInternal(visitSet);

        Collection<Visit> visits = pet.getVisits();
        assertEquals(2, visits.size(), "Should be two visits");
    }
}
