// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.util.Collection;
import java.util.LinkedHashSet;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.samples.petclinic.visit.Visit;

public class Pet_getVisits_e2a563d9d4_Test {

    private Pet pet;

    @BeforeEach
    public void setup() {
        pet = new Pet();
    }

    @Test
    public void testGetVisitsWhenVisitsExist() {
        Visit visit1 = new Visit();
        Visit visit2 = new Visit();
        Set<Visit> visitSet = new LinkedHashSet<>();
        visitSet.add(visit1);
        visitSet.add(visit2);
        pet.setVisits(visitSet);

        Collection<Visit> result = pet.getVisits();

        assertEquals(2, result.size(), "Expected 2 visits");
        assertTrue(result.contains(visit1), "Expected result to contain visit1");
        assertTrue(result.contains(visit2), "Expected result to contain visit2");
    }

    @Test
    public void testGetVisitsWhenNoVisitsExist() {
        Collection<Visit> result = pet.getVisits();
        assertTrue(result.isEmpty(), "Expected no visits");
    }
}
