// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;
import java.time.LocalDate;

public class Pet_getBirthDate_7f1e9ebfb7_Test {

    @Test
    public void testGetBirthDate() {
        Pet pet = new Pet();
        LocalDate birthDate = LocalDate.of(2020, 1, 1);
        pet.setBirthDate(birthDate);
        assertEquals(birthDate, pet.getBirthDate());
    }

    @Test
    public void testGetBirthDateNull() {
        Pet pet = new Pet();
        assertEquals(null, pet.getBirthDate());
    }
}
