// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.samples.petclinic.model.Pet;
import org.springframework.samples.petclinic.model.PetType;

public class Pet_setType_9a8aa62bfe_Test {

    private Pet pet;

    @BeforeEach
    public void setUp() {
        pet = new Pet();
    }

    @Test
    public void testSetType() {
        PetType type = new PetType();
        type.setName("Dog");
        pet.setType(type);
        assertEquals("Dog", pet.getType().getName());
    }

    @Test
    public void testSetTypeNull() {
        pet.setType(null);
        assertNull(pet.getType());
    }
}
