// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;

import java.util.Collection;
import java.util.LinkedHashSet;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.samples.petclinic.model.Visit;


public class Pet_getVisits_e2a563d9d4_Test {

    private Pet pet;

    @BeforeEach
    public void setup() {
        pet = new Pet();
    }

    @Test
    public void testGetVisits_whenNoVisits() {
        Collection<Visit> visits = pet.getVisits();
        assertNotNull(visits, "Visits should not be null");
        assertEquals(0, visits.size(), "Visits should be empty");
    }

    @Test
    public void testGetVisits_whenThereAreVisits() {
        Set<Visit> visits = new LinkedHashSet<>();
        Visit visit1 = new Visit();
        Visit visit2 = new Visit();
        visits.add(visit1);
        visits.add(visit2);
        pet.setVisits(visits);

        Collection<Visit> actualVisits = pet.getVisits();
        assertNotNull(actualVisits, "Visits should not be null");
        assertEquals(2, actualVisits.size(), "There should be two visits");
    }
}
