// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.samples.petclinic.visit.Visit;

import static org.junit.jupiter.api.Assertions.assertTrue;

@ExtendWith(MockitoExtension.class)
public class Pet_addVisit_f1d5eb0dda_Test {

    @InjectMocks
    Pet pet;

    @Test
    public void testAddVisit() {
        Visit visit = new Visit();
        pet.addVisit(visit);
        assertTrue(pet.getVisits().contains(visit), "The visit should be added to the pet.");
    }

    @Test
    public void testAddVisit_NullVisit() {
        Visit visit = null;
        pet.addVisit(visit);
        assertTrue(!pet.getVisits().contains(visit), "Null visit should not be added to the pet.");
    }
}
