// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import java.util.LinkedHashSet;
import java.util.Set;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.samples.petclinic.model.Visit;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
public class Pet_addVisit_f1d5eb0dda_Test {

    @Mock
    private Pet pet;

    @Mock
    private Visit visit;

    private Set<Visit> visits;

    @BeforeEach
    void setUp() {
        visits = new LinkedHashSet<>();
        when(pet.getVisits()).thenReturn(visits);
    }

    @Test
    void testAddVisitWithEmptyVisits() {
        pet.addVisit(visit);
        assertTrue(visits.contains(visit));
    }

    @Test
    void testAddVisitWithExistingVisits() {
        Visit existingVisit = mock(Visit.class);
        visits.add(existingVisit);
        
        pet.addVisit(visit);
        assertTrue(visits.contains(visit));
        assertTrue(visits.contains(existingVisit));
    }
}
