// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.ui.ModelMap;

public class PetController_initCreationForm_5bf7d6624b_Test {

    private PetController petController;
    private Owner owner;
    private ModelMap model;

    @BeforeEach
    public void setup() {
        petController = new PetController();
        owner = mock(Owner.class);
        model = new ModelMap();
    }

    @Test
    public void testInitCreationForm() {
        when(owner.addPet(any(Pet.class))).thenReturn(any(Pet.class));

        String view = petController.initCreationForm(owner, model);

        verify(owner).addPet(any(Pet.class));
        assertEquals("pets/createOrUpdatePetForm", view);
        assertEquals(owner.getPets().size(), 1);
    }

    @Test
    public void testInitCreationFormWithExistingPet() {
        Pet existingPet = new Pet();
        owner.addPet(existingPet);

        String view = petController.initCreationForm(owner, model);

        verify(owner).addPet(any(Pet.class));
        assertEquals("pets/createOrUpdatePetForm", view);
        assertEquals(owner.getPets().size(), 2);
    }
}
