// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.validation.BeanPropertyBindingResult;
import org.springframework.web.bind.WebDataBinder;

import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.junit.jupiter.api.Assertions.assertFalse;

public class PetController_initOwnerBinder_c48260f88f_Test {

    private WebDataBinder dataBinder;

    @BeforeEach
    public void setup() {
        dataBinder = new WebDataBinder(new Object());
    }

    @Test
    public void testInitOwnerBinder_DisallowedId() {
        PetController controller = new PetController();
        controller.initOwnerBinder(dataBinder);

        BeanPropertyBindingResult result = new BeanPropertyBindingResult(dataBinder.getTarget(), "target");
        dataBinder.validate(result);

        assertTrue(result.hasFieldErrors("id"));
    }

    @Test
    public void testInitOwnerBinder_AllowedName() {
        PetController controller = new PetController();
        controller.initOwnerBinder(dataBinder);

        BeanPropertyBindingResult result = new BeanPropertyBindingResult(dataBinder.getTarget(), "target");
        dataBinder.validate(result);

        assertFalse(result.hasFieldErrors("name"));
    }
}
