// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import java.util.HashMap;
import java.util.Map;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.ui.ModelMap;

public class PetController_initCreationForm_5bf7d6624b_Test {
    private PetController petController;
    private Owner owner;
    private ModelMap model;

    @BeforeEach
    void setup() {
        petController = new PetController();
        owner = mock(Owner.class);
        model = new ModelMap();
    }

    @Test
    void testInitCreationForm() {
        String viewName = petController.initCreationForm(owner, model);
        assertEquals("pets/createOrUpdateForm", viewName);

        verify(owner).addPet(model.get("pet"));
    }

    @Test
    void testInitCreationFormWithMockModel() {
        ModelMap mockModel = mock(ModelMap.class);
        Map<String, Object> map = new HashMap<>();
        when(mockModel.put("pet", new Pet())).thenReturn(map.put("pet", new Pet()));

        String viewName = petController.initCreationForm(owner, mockModel);
        assertEquals("pets/createOrUpdateForm", viewName);

        verify(mockModel).put("pet", new Pet());
        verify(owner).addPet(map.get("pet"));
    }
}
