// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import static org.mockito.Mockito.when;
import static org.junit.jupiter.api.Assertions.assertEquals;

import java.util.Optional;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

public class PetController_PetController_2a2536f183_Test {

    @Mock
    private OwnerRepository owners;

    @InjectMocks
    private PetController petController;

    @BeforeEach
    public void init() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testPetControllerWithValidOwner() {
        Owner owner = new Owner();
        owner.setId(1);
        
        when(owners.findById(1)).thenReturn(Optional.of(owner));
        
        PetController controller = new PetController(owners);
        
        assertEquals(controller.getOwner().getId(), owner.getId());
    }

    @Test
    public void testPetControllerWithInvalidOwner() {
        when(owners.findById(1)).thenReturn(Optional.empty());

        PetController controller = new PetController(owners);

        assertEquals(controller.getOwner(), null);
    }
}
