// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.ui.ModelMap;

public class PetController_initUpdateForm_4cd21e8292_Test {

    private static final int PET_ID = 1;
    private static final String VIEWS_PETS_CREATE_OR_UPDATE_FORM = "pets/createOrUpdatePetForm";

    private Owner owner;
    private Pet pet;
    private ModelMap model;

    @BeforeEach
    public void setup() {
        owner = mock(Owner.class);
        pet = mock(Pet.class);
        model = new ModelMap();

        when(owner.getPet(PET_ID)).thenReturn(pet);
    }

    @Test
    public void testInitUpdateForm() {
        PetController petController = new PetController();
        String view = petController.initUpdateForm(owner, PET_ID, model);

        assertEquals(VIEWS_PETS_CREATE_OR_UPDATE_FORM, view);
        assertEquals(pet, model.get("pet"));
    }

    @Test
    public void testInitUpdateFormWithInvalidPetId() {
        when(owner.getPet(PET_ID)).thenReturn(null);

        PetController petController = new PetController();
        String view = petController.initUpdateForm(owner, PET_ID, model);

        assertEquals(VIEWS_PETS_CREATE_OR_UPDATE_FORM, view);
        assertEquals(null, model.get("pet"));
    }
}
