// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
public class PetController_findOwner_0895b41fd2_Test {

    @Mock
    private OwnerRepository owners;

    @InjectMocks
    private PetController petController;

    @BeforeEach
    void setup() {
        Owner owner = new Owner();
        owner.setId(1);
        when(owners.findById(1)).thenReturn(owner);
    }

    @Test
    public void testFindOwner_success() {
        Owner owner = petController.findOwner(1);
        assertNotNull(owner);
        assertEquals(1, owner.getId());
    }

    @Test
    public void testFindOwner_failure() {
        Exception exception = assertThrows(IllegalArgumentException.class, () -> {
            petController.findOwner(0);
        });

        String expectedMessage = "Owner ID not found: 0";
        String actualMessage = exception.getMessage();

        assertTrue(actualMessage.contains(expectedMessage));
    }
}
