// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import java.time.LocalDate;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import org.springframework.ui.ModelMap;
import org.springframework.validation.BindingResult;

public class PetController_processUpdateForm_8b32776c46_Test {

    @Mock
    private BindingResult result;

    @Mock
    private ModelMap model;

    @Mock
    private Owner owner;

    @Mock
    private Pet pet;

    private PetController petController;

    private static final String VIEWS_PETS_CREATE_OR_UPDATE_FORM = "pets/createOrUpdatePetForm";

    @BeforeEach
    public void setup() {
        MockitoAnnotations.initMocks(this);
        petController = new PetController();
    }

    @Test
    public void testProcessUpdateForm_success() {
        when(result.hasErrors()).thenReturn(false);
        when(pet.getName()).thenReturn("Fluffy");
        when(owner.getPet("fluffy", false)).thenReturn(null);
        when(pet.getBirthDate()).thenReturn(LocalDate.now().minusYears(1));

        String view = petController.processUpdateForm(pet, result, owner, model);

        verify(owner).addPet(pet);
        assertEquals("redirect:/owners/{ownerId}", view);
    }

    @Test
    public void testProcessUpdateForm_duplicatePetName() {
        when(result.hasErrors()).thenReturn(true);
        when(pet.getName()).thenReturn("Fluffy");
        Pet existingPet = new Pet();
        existingPet.setId(2);
        when(owner.getPet("fluffy", false)).thenReturn(existingPet);
        when(pet.getId()).thenReturn(1);

        String view = petController.processUpdateForm(pet, result, owner, model);

        verify(result).rejectValue("name", "duplicate", "already exists");
        assertEquals(VIEWS_PETS_CREATE_OR_UPDATE_FORM, view);
    }

    @Test
    public void testProcessUpdateForm_futureBirthDate() {
        when(result.hasErrors()).thenReturn(true);
        when(pet.getBirthDate()).thenReturn(LocalDate.now().plusDays(1));

        String view = petController.processUpdateForm(pet, result, owner, model);

        verify(result).rejectValue("birthDate", "typeMismatch.birthDate");
        assertEquals(VIEWS_PETS_CREATE_OR_UPDATE_FORM, view);
    }
}
