// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Spy;
import org.springframework.validation.DataBinder;

import static org.mockito.Mockito.verify;
import static org.mockito.MockitoAnnotations.initMocks;

public class PetController_initOwnerBinder_c48260f88f_Test {

    @Spy
    private DataBinder dataBinder;

    private PetController petController;

    @BeforeEach
    void setup() {
        initMocks(this);
        petController = new PetController();
    }

    @Test
    void testInitOwnerBinder() {
        petController.initOwnerBinder(dataBinder);
        verify(dataBinder).setDisallowedFields("id");
    }

    @Test
    void testInitOwnerBinderWithDifferentField() {
        dataBinder.setDisallowedFields("name");
        petController.initOwnerBinder(dataBinder);
        verify(dataBinder).setDisallowedFields("id");
    }
}
