// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.when;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import org.springframework.ui.ModelMap;

public class PetController_initUpdateForm_4cd21e8292_Test {

    private static final int PET_ID = 1;
    private static final String VIEWS_PETS_CREATE_OR_UPDATE_FORM = "pets/createOrUpdatePetForm";

    @Mock
    private Owner owner;

    @Mock
    private Pet pet;

    @Mock
    private ModelMap model;

    @BeforeEach
    public void setup() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testInitUpdateFormSuccess() {
        when(owner.getPet(PET_ID)).thenReturn(pet);

        String view = initUpdateForm(owner, PET_ID, model);

        assertEquals(VIEWS_PETS_CREATE_OR_UPDATE_FORM, view);
    }

    @Test
    public void testInitUpdateFormFailure() {
        when(owner.getPet(PET_ID)).thenReturn(null);

        String view = initUpdateForm(owner, PET_ID, model);

        assertEquals(VIEWS_PETS_CREATE_OR_UPDATE_FORM, view);
    }

    private String initUpdateForm(Owner owner, int petId, ModelMap model) {
        Pet pet = owner.getPet(petId);
        model.put("pet", pet);
        return VIEWS_PETS_CREATE_OR_UPDATE_FORM;
    }
}
