// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import static org.mockito.Mockito.mock;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import org.springframework.validation.Validator;
import org.springframework.web.bind.WebDataBinder;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

public class PetController_initPetBinder_548d74aca4_Test {

    private WebDataBinder dataBinder;

    @BeforeEach
    public void setup() {
        dataBinder = mock(WebDataBinder.class);
    }

    @Test
    public void testInitPetBinder() {
        PetController petController = new PetController();
        petController.initPetBinder(dataBinder);
        Validator validator = dataBinder.getValidator();
        assertNotNull(validator, "Validator should not be null");
    }

    @Test
    public void testInitPetBinderWithNullDataBinder() {
        PetController petController = new PetController();
        try {
            petController.initPetBinder(null);
        } catch (Exception e) {
            assertNotNull(e, "Exception should not be null");
        }
    }
}
