// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.when;
import java.util.ArrayList;
import java.util.Collection;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

@ExtendWith(MockitoExtension.class)
public class PetController_populatePetTypes_68489030ac_Test {

    @InjectMocks
    PetController petController;

    @Mock
    OwnerService owners;

    Collection<PetType> petTypes;

    @BeforeEach
    void setup() {
        petTypes = new ArrayList<>();
        PetType petType1 = new PetType();
        petType1.setName("Dog");
        petTypes.add(petType1);

        PetType petType2 = new PetType();
        petType2.setName("Cat");
        petTypes.add(petType2);
    }

    @Test
    void testPopulatePetTypes() {
        when(owners.findPetTypes()).thenReturn(petTypes);
        Collection<PetType> returnedPetTypes = petController.populatePetTypes();
        assertEquals(petTypes, returnedPetTypes);
    }

    @Test
    void testPopulatePetTypes_empty() {
        petTypes.clear();
        when(owners.findPetTypes()).thenReturn(petTypes);
        Collection<PetType> returnedPetTypes = petController.populatePetTypes();
        assertEquals(petTypes, returnedPetTypes);
    }
}
