// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.web.bind.WebDataBinder;

import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.verify;

@ExtendWith(MockitoExtension.class)
public class PetController_initOwnerBinder_c48260f88f_Test {

    @InjectMocks
    PetController petController;

    @Test
    public void testInitOwnerBinder() {
        WebDataBinder dataBinder = mock(WebDataBinder.class);

        petController.initOwnerBinder(dataBinder);

        verify(dataBinder).setDisallowedFields("id");
    }

    @Test
    public void testInitOwnerBinderWithNull() {
        WebDataBinder dataBinder = null;

        petController.initOwnerBinder(dataBinder);

        verify(dataBinder).setDisallowedFields("id");
    }
}
