// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

public class PetController_PetController_2a2536f183_Test {

    @Mock
    private OwnerRepository owners;

    @InjectMocks
    private PetController petController;

    @BeforeEach
    public void init() {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testPetController() {
        Owner owner = new Owner();
        owner.setId(1);

        when(owners.findById(anyInt())).thenReturn(owner);

        PetController petControllerMock = new PetController(owners);
        assertNotNull(petControllerMock);
    }

    @Test
    public void testPetControllerWithNull() {
        assertThrows(NullPointerException.class, () -> new PetController(null));
    }
}
