// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.samples.petclinic.owner.PetType;

public class PetController_populatePetTypes_68489030ac_Test {

    private OwnerRepository owners;
    private PetController petController;

    @BeforeEach
    public void setup() {
        owners = mock(OwnerRepository.class);
        petController = new PetController(owners, null, null);
    }

    @Test
    public void testPopulatePetTypes() {
        PetType dog = new PetType();
        dog.setName("dog");
        PetType cat = new PetType();
        cat.setName("cat");
        List<PetType> petTypes = Arrays.asList(dog, cat);

        when(owners.findPetTypes()).thenReturn(petTypes);

        Collection<PetType> populatedPetTypes = petController.populatePetTypes();
        assertEquals(2, populatedPetTypes.size());
        assertEquals("dog", populatedPetTypes.iterator().next().getName());
    }

    @Test
    public void testPopulatePetTypesWithNoPetTypes() {
        when(owners.findPetTypes()).thenReturn(null);

        Collection<PetType> populatedPetTypes = petController.populatePetTypes();
        assertEquals(0, populatedPetTypes.size());
    }
}
