// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;
import org.junit.jupiter.api.Test;
import org.springframework.ui.ModelMap;

public class PetController_initCreationForm_5bf7d6624b_Test {
    private static final String VIEWS_PETS_CREATE_OR_UPDATE_FORM = "pets/createOrUpdatePetForm";

    @Test
    public void testInitCreationForm() {
        Owner owner = new Owner();
        ModelMap model = mock(ModelMap.class);

        String result = initCreationForm(owner, model);

        assertEquals(VIEWS_PETS_CREATE_OR_UPDATE_FORM, result);
        assertEquals(owner.getPets().size(), 1);
    }

    @Test
    public void testInitCreationForm_WithExistingPet() {
        Owner owner = new Owner();
        Pet existingPet = new Pet();
        owner.addPet(existingPet);
        ModelMap model = mock(ModelMap.class);

        String result = initCreationForm(owner, model);

        assertEquals(VIEWS_PETS_CREATE_OR_UPDATE_FORM, result);
        assertEquals(owner.getPets().size(), 2);
    }
}
