// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

import org.junit.jupiter.api.Test;
import org.springframework.ui.ModelMap;

public class PetController_initUpdateForm_4cd21e8292_Test {

    @Test
    public void testInitUpdateForm() {
        Owner owner = mock(Owner.class);
        ModelMap model = new ModelMap();
        Pet pet = new Pet();
        pet.setId(1);

        when(owner.getPet(1)).thenReturn(pet);

        PetController controller = new PetController();
        String viewName = controller.initUpdateForm(owner, 1, model);

        assertEquals("pets/createOrUpdatePetForm", viewName);
        assertEquals(pet, model.get("pet"));
    }

    @Test
    public void testInitUpdateFormWithInvalidPetId() {
        Owner owner = mock(Owner.class);
        ModelMap model = new ModelMap();

        when(owner.getPet(2)).thenReturn(null);

        PetController controller = new PetController();
        String viewName = controller.initUpdateForm(owner, 2, model);

        assertEquals("pets/createOrUpdatePetForm", viewName);
        assertEquals(null, model.get("pet"));
    }
}
