// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.when;

import java.util.Arrays;
import java.util.Collection;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import org.springframework.samples.petclinic.owner.PetController;
import org.springframework.samples.petclinic.owner.PetType;

public class PetController_populatePetTypes_68489030ac_Test {
	
	@Mock
	private OwnerRepository owners;
	
	@InjectMocks
	private PetController petController;
	
	@BeforeEach
	public void init() {
		MockitoAnnotations.initMocks(this);
	}
	
	@Test
	public void testPopulatePetTypes() {
		PetType dog = new PetType();
		dog.setName("Dog");
		PetType cat = new PetType();
		cat.setName("Cat");
		
		when(owners.findPetTypes()).thenReturn(Arrays.asList(dog, cat));
		
		Collection<PetType> petTypes = petController.populatePetTypes();
		
		assertEquals(2, petTypes.size());
	}
	
	@Test
	public void testPopulatePetTypes_empty() {
		when(owners.findPetTypes()).thenReturn(Arrays.asList());
		
		Collection<PetType> petTypes = petController.populatePetTypes();
		
		assertEquals(0, petTypes.size());
	}
}
