// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.MockitoJUnitRunner;
import org.springframework.context.MessageSource;

import java.util.Locale;

import static org.junit.Assert.assertEquals;
import static org.mockito.Mockito.when;

@RunWith(MockitoJUnitRunner.class)
public class PetTypeFormatter_print_77be636728_Test {

    @Mock
    private MessageSource messageSource;

    @InjectMocks
    private PetTypeFormatter petTypeFormatter;

    @Mock
    private PetType petType;

    @Before
    public void setup() {
        when(petType.getName()).thenReturn("Dog");
    }

    @Test
    public void print_ValidPetType_ReturnsPetTypeName() {
        String result = petTypeFormatter.print(petType, Locale.US);
        assertEquals("Dog", result);
    }

    @Test(expected = NullPointerException.class)
    public void print_NullPetType_ThrowsNullPointerException() {
        petTypeFormatter.print(null, Locale.US);
    }
}
