// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.test.context.junit4.SpringRunner;

import java.text.ParseException;
import java.util.Arrays;
import java.util.Locale;

import static org.junit.Assert.assertEquals;
import static org.mockito.Mockito.when;

@RunWith(SpringRunner.class)
@SpringBootTest
public class PetTypeFormatter_parse_2ffcaf4072_Test {

    @Autowired
    PetTypeFormatter petTypeFormatter;

    @MockBean
    private OwnerRepository owners;

    @Test
    public void testParse_success() throws ParseException {
        PetType dogType = new PetType();
        dogType.setName("Dog");

        when(owners.findPetTypes()).thenReturn(Arrays.asList(dogType));

        PetType result = petTypeFormatter.parse("Dog", Locale.ENGLISH);

        assertEquals(dogType, result);
    }

    @Test(expected = ParseException.class)
    public void testParse_typeNotFound() throws ParseException {
        PetType dogType = new PetType();
        dogType.setName("Dog");

        when(owners.findPetTypes()).thenReturn(Arrays.asList(dogType));

        petTypeFormatter.parse("Cat", Locale.ENGLISH);
    }
}
