// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.format.Formatter;

import java.text.ParseException;
import java.util.Locale;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.mockito.Mockito.when;

@ExtendWith(MockitoExtension.class)
public class PetTypeFormatter_PetTypeFormatter_d71c071163_Test {

    @Mock
    private OwnerRepository owners;

    @InjectMocks
    private PetTypeFormatter petTypeFormatter;

    private PetType petType;

    @BeforeEach
    public void setup() {
        petType = new PetType();
        petType.setId(1);
        petType.setName("Dog");
    }

    @Test
    public void testPrint() {
        String petTypeName = petTypeFormatter.print(petType, Locale.ENGLISH);
        assertEquals("Dog", petTypeName);
    }

    @Test
    public void testParse_Success() throws ParseException {
        when(owners.findPetTypes()).thenReturn(List.of(petType));
        PetType parsedPetType = petTypeFormatter.parse("Dog", Locale.ENGLISH);
        assertEquals(petType, parsedPetType);
    }

    @Test
    public void testParse_Failure() {
        when(owners.findPetTypes()).thenReturn(List.of(petType));
        assertThrows(ParseException.class, () -> petTypeFormatter.parse("Cat", Locale.ENGLISH));
    }
}
