// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import org.springframework.beans.factory.annotation.Autowired;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import java.text.ParseException;
import java.util.Arrays;
import java.util.Locale;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.mockito.Mockito.when;

@ExtendWith(MockitoExtension.class)
public class PetTypeFormatter_parse_2ffcaf4072_Test {

    @Autowired
    Locale locale;

    @InjectMocks
    PetTypeFormatter petTypeFormatter;

    @Mock
    OwnerService owners;

    @Test
    public void testParse_success() throws ParseException {
        PetType dog = new PetType();
        dog.setName("Dog");

        PetType cat = new PetType();
        cat.setName("Cat");

        when(owners.findPetTypes()).thenReturn(Arrays.asList(dog, cat));

        PetType petType = petTypeFormatter.parse("Dog", locale);
        assertEquals("Dog", petType.getName());
    }

    @Test
    public void testParse_failure() {
        PetType dog = new PetType();
        dog.setName("Dog");

        when(owners.findPetTypes()).thenReturn(Arrays.asList(dog));

        assertThrows(ParseException.class, () -> petTypeFormatter.parse("Cat", locale));
    }
}
