// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.mock.mockito.MockBean;

import java.util.Locale;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.when;

@SpringBootTest
public class PetTypeFormatter_print_77be636728_Test {

    @Autowired
    private PetTypeFormatter petTypeFormatter;

    @MockBean
    private PetType petType;

    @Test
    public void testPrintSuccess() {
        String petTypeName = "Dog";
        when(petType.getName()).thenReturn(petTypeName);
        String result = petTypeFormatter.print(petType, Locale.US);
        assertEquals(petTypeName, result);
    }

    @Test
    public void testPrintFailure() {
        String petTypeName = null;
        when(petType.getName()).thenReturn(petTypeName);
        String result = petTypeFormatter.print(petType, Locale.US);
        assertEquals(petTypeName, result);
    }
}
