// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import org.springframework.util.StringUtils;
import org.springframework.validation.Errors;
import org.springframework.validation.Validator;

import java.time.LocalDate;

import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

public class PetValidator_validate_7f6b8f81d8_Test {

    @Mock
    private Errors errors;

    private Pet pet;

    private Validator petValidator;

    @BeforeEach
    public void setup() {
        MockitoAnnotations.initMocks(this);
        pet = new Pet();
        petValidator = new PetValidator();
    }

    @Test
    public void testValidate_NameIsEmpty() {
        pet.setName("");
        petValidator.validate(pet, errors);
        verify(errors).rejectValue("name", "required", "required");
    }

    @Test
    public void testValidate_TypeIsNull() {
        pet.setName("Fluffy");
        pet.setBirthDate(LocalDate.now());
        petValidator.validate(pet, errors);
        verify(errors).rejectValue("type", "required", "required");
    }

    @Test
    public void testValidate_BirthDateIsNull() {
        pet.setName("Fluffy");
        pet.setType(new PetType());
        petValidator.validate(pet, errors);
        verify(errors).rejectValue("birthDate", "required", "required");
    }

    @Test
    public void testValidate_AllFieldsValid() {
        pet.setName("Fluffy");
        pet.setType(new PetType());
        pet.setBirthDate(LocalDate.now());
        petValidator.validate(pet, errors);
        verify(errors, never()).rejectValue(anyString(), anyString(), anyString());
    }
}
