// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import org.junit.jupiter.api.Test;
import org.springframework.samples.petclinic.visit.Visit;
import static org.junit.jupiter.api.Assertions.*;

public class PetValidator_supports_dc90d51349_Test {

    @Test
    public void testSupports_PetClass() {
        PetValidator validator = new PetValidator();
        assertTrue(validator.supports(Pet.class), "Expected supports() to return true for Pet class");
    }

    @Test
    public void testSupports_SubclassOfPet() {
        PetValidator validator = new PetValidator();
        assertTrue(validator.supports(NamedPet.class), "Expected supports() to return true for subclass of Pet");
    }

    @Test
    public void testSupports_NotPetClass() {
        PetValidator validator = new PetValidator();
        assertFalse(validator.supports(Visit.class), "Expected supports() to return false for non-Pet class");
    }

    // TODO: Replace NamedPet with a real subclass of Pet if exists
    private static class NamedPet extends Pet {}

}
