// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.validation.BeanPropertyBindingResult;
import org.springframework.validation.Errors;

import java.time.LocalDate;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class PetValidator_validate_7f6b8f81d8_Test {
    private PetValidator petValidator;
    private Pet pet;
    private Errors errors;

    @BeforeEach
    void setup() {
        petValidator = new PetValidator();
        pet = new Pet();
        errors = new BeanPropertyBindingResult(pet, "pet");
    }

    @Test
    void shouldRejectEmptyName() {
        pet.setName("");
        petValidator.validate(pet, errors);
        assertEquals(errors.getFieldError("name").getCode(), "REQUIRED");
    }

    @Test
    void shouldRejectNullTypeForNewPet() {
        pet.setNew(true);
        petValidator.validate(pet, errors);
        assertEquals(errors.getFieldError("type").getCode(), "REQUIRED");
    }

    @Test
    void shouldRejectNullBirthDate() {
        petValidator.validate(pet, errors);
        assertEquals(errors.getFieldError("birthDate").getCode(), "REQUIRED");
    }

    @Test
    void shouldValidatePetWithCorrectFields() {
        pet.setName("Test");
        pet.setType(new PetType());
        pet.setBirthDate(LocalDate.now());
        petValidator.validate(pet, errors);
        assertEquals(errors.getErrorCount(), 0);
    }
}
