// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.springframework.util.StringUtils;
import org.springframework.validation.Errors;
import org.springframework.validation.Validator;

public class PetValidator_supports_dc90d51349_Test {

    private final PetValidator petValidator = new PetValidator();

    @Test
    public void testSupports_withPetClass() {
        boolean result = petValidator.supports(Pet.class);
        Assertions.assertTrue(result, "Supports method should return true when Pet.class is passed as parameter");
    }

    @Test
    public void testSupports_withNonPetClass() {
        boolean result = petValidator.supports(String.class);
        Assertions.assertFalse(result, "Supports method should return false when non-Pet.class is passed as parameter");
    }
}
