// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.samples.petclinic.owner.Pet;
import org.springframework.samples.petclinic.owner.PetValidator;

import static org.junit.jupiter.api.Assertions.*;

class PetValidator_supports_dc90d51349_Test {

    private PetValidator petValidator;

    @BeforeEach
    void setUp() {
        petValidator = new PetValidator();
    }

    @Test
    void supports_withPetClass_shouldReturnTrue() {
        boolean result = petValidator.supports(Pet.class);
        assertTrue(result, "Expected supports to return true for Pet class");
    }

    @Test
    void supports_withNonPetClass_shouldReturnFalse() {
        boolean result = petValidator.supports(String.class);
        assertFalse(result, "Expected supports to return false for non-Pet class");
    }
}
