// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.samples.petclinic.visit.Visit;

import java.time.LocalDate;

import static org.junit.jupiter.api.Assertions.*;

public class Visit_Visit_02adeb17dc_Test {

    private Visit visit;

    @BeforeEach
    public void setUp() {
        visit = new Visit();
    }

    @Test
    public void testVisitDateToday() {
        LocalDate expectedDate = LocalDate.now();
        assertEquals(expectedDate, visit.getDate());
    }

    @Test
    public void testVisitDateNotTomorrow() {
        LocalDate expectedDate = LocalDate.now().plusDays(1);
        assertNotEquals(expectedDate, visit.getDate());
    }
}
