// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.samples.petclinic.model.BaseEntity;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.mock.mockito.MockBean;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.when;

@SpringBootTest
public class Visit_getDescription_b1844ea396_Test {

    @MockBean
    private BaseEntity baseEntity;

    @BeforeEach
    public void setUp() {
        when(baseEntity.getDescription()).thenReturn("Test description");
    }

    @Test
    public void testGetDescriptionSuccess() {
        String description = baseEntity.getDescription();
        assertEquals("Test description", description);
    }

    @Test
    public void testGetDescriptionFailure() {
        when(baseEntity.getDescription()).thenReturn(null);
        String description = baseEntity.getDescription();
        assertEquals(null, description);
    }
}
