// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import java.time.LocalDate;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.samples.petclinic.model.BaseEntity;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class Visit_getDate_efa9e4d8bf_Test {

    private BaseEntity testEntity;

    @BeforeEach
    public void setup() {
        testEntity = new BaseEntity();
    }

    @Test
    public void testGetDateWhenDateIsSet() {
        LocalDate expectedDate = LocalDate.of(2022, 1, 1);
        testEntity.setDate(expectedDate);
        LocalDate actualDate = testEntity.getDate();
        assertEquals(expectedDate, actualDate, "The actual date does not match the expected date");
    }

    @Test
    public void testGetDateWhenDateIsNotSet() {
        LocalDate actualDate = testEntity.getDate();
        assertEquals(null, actualDate, "The actual date is not null when it should be");
    }
}
