// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.when;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.validation.BindingResult;

@ExtendWith(MockitoExtension.class)
public class VisitController_processNewVisitForm_7a4a412d78_Test {

    @Mock
    private Owner owner;

    @Mock
    private BindingResult result;

    @InjectMocks
    private VisitController visitController;

    private int petId;
    private Visit visit;

    @BeforeEach
    void setup() {
        petId = 1;
        visit = new Visit();
    }

    @Test
    void testProcessNewVisitFormWithErrors() {
        when(result.hasErrors()).thenReturn(true);

        String view = visitController.processNewVisitForm(owner, petId, visit, result);

        assertEquals("pets/createOrUpdateVisitForm", view);
    }

    @Test
    void testProcessNewVisitFormWithoutErrors() {
        when(result.hasErrors()).thenReturn(false);

        String view = visitController.processNewVisitForm(owner, petId, visit, result);

        assertEquals("redirect:/owners/{ownerId}", view);
    }
}
