// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import java.time.LocalDate;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.springframework.samples.petclinic.visit.Visit;

public class Visit_Visit_02adeb17dc_Test {

    @Test
    public void testVisitConstructor() {
        Visit visit = new Visit();
        Assertions.assertNotNull(visit.getDate(), "Date should not be null");
        Assertions.assertEquals(LocalDate.now(), visit.getDate(), "Date should be equal to current date");
    }

    @Test
    public void testVisitConstructorWithFutureDate() {
        LocalDate futureDate = LocalDate.now().plusDays(1);
        Visit visit = new Visit(futureDate);
        Assertions.assertNotNull(visit.getDate(), "Date should not be null");
        Assertions.assertEquals(futureDate, visit.getDate(), "Date should be equal to future date");
    }
}
