// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.Mock;
import org.mockito.junit.MockitoJUnitRunner;
import org.springframework.web.bind.WebDataBinder;

import static org.mockito.Mockito.verify;

@RunWith(MockitoJUnitRunner.class)
public class VisitController_setAllowedFields_6961bda542_Test {

    @Mock
    private WebDataBinder dataBinder;

    private VisitController visitController;

    @Before
    public void setup() {
        visitController = new VisitController();
    }

    @Test
    public void testSetAllowedFields() {
        visitController.setAllowedFields(dataBinder);
        verify(dataBinder).setDisallowedFields("id");
    }

    @Test
    public void testSetAllowedFieldsWithDifferentInput() {
        // TODO: Replace "newId" with appropriate value
        dataBinder.setDisallowedFields("newId");
        visitController.setAllowedFields(dataBinder);
        verify(dataBinder).setDisallowedFields("id");
    }
}
