// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import java.time.LocalDate;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import org.springframework.samples.petclinic.model.BaseEntity;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class Visit_getDate_efa9e4d8bf_Test {

    private BaseEntity visit;
    private LocalDate testDate;

    @BeforeEach
    public void setup() {
        visit = new BaseEntity();
        testDate = LocalDate.now();
        visit.setDate(testDate);
    }

    @Test
    public void testGetDate() {
        LocalDate result = visit.getDate();
        assertEquals(testDate, result, "Returned date should match the set date");
    }

    @Test
    public void testGetDateWhenDateNotSet() {
        visit = new BaseEntity();
        LocalDate result = visit.getDate();
        assertEquals(null, result, "Returned date should be null when date is not set");
    }

}
