// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.WebDataBinder;

class VisitController_setAllowedFields_6961bda542_Test {

    private WebDataBinder dataBinder;

    @BeforeEach
    void setUp() {
        dataBinder = new WebDataBinder(null);
    }

    @Test
    void testSetAllowedFields_noDisallowedFields() {
        setAllowedFields(dataBinder);
        assertNull(dataBinder.getDisallowedFields());
    }

    @Test
    void testSetAllowedFields_checkDisallowedField() {
        setAllowedFields(dataBinder);
        String[] disallowedFields = dataBinder.getDisallowedFields();
        assertEquals(1, disallowedFields.length);
        assertEquals("id", disallowedFields[0]);
    }

    public void setAllowedFields(WebDataBinder dataBinder) {
        dataBinder.setDisallowedFields("id");
    }
}
