// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import java.time.LocalDate;
import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.samples.petclinic.model.BaseEntity;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class Visit_setDate_c4566f8342_Test {

    @Test
    public void testSetDate() {
        BaseEntity testEntity = new BaseEntity();
        LocalDate testDate = LocalDate.of(2022, 1, 1);
        testEntity.setDate(testDate);
        assertEquals(testDate, testEntity.getDate());
    }

    @Test
    public void testSetDateWithNull() {
        BaseEntity testEntity = new BaseEntity();
        testEntity.setDate(null);
        assertEquals(null, testEntity.getDate());
    }
}
