// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.extension.ExtendWith;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit.jupiter.SpringExtension;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.ui.Model;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.Mockito.mock;

@ExtendWith(SpringExtension.class)
@SpringBootTest
public class VisitController_initNewVisitForm_de58f9a1b2_Test {

    @Autowired
    private VisitController visitController;

    private Model model;

    @BeforeEach
    public void setup() {
        model = mock(Model.class);
    }

    @Test
    public void testInitNewVisitForm_Success() {
        String view = visitController.initNewVisitForm(model);
        assertThat(view).isEqualTo("pets/createOrUpdateVisitForm");
    }

    @Test
    public void testInitNewVisitForm_Failure() {
        String view = visitController.initNewVisitForm(model);
        assertThat(view).isNotEqualTo("pets/wrongForm");
    }
}
