// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import org.junit.jupiter.api.Test;
import org.springframework.samples.petclinic.model.Visit;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;

public class Visit_setDescription_b4ccff923c_Test {

    @Test
    public void testSetDescription() {
        Visit visit = new Visit();
        String description = "A regular check-up";
        visit.setDescription(description);
        assertEquals(description, visit.getDescription());
    }

    @Test
    public void testSetDescriptionNull() {
        Visit visit = new Visit();
        visit.setDescription(null);
        assertNull(visit.getDescription());
    }
}
