// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import java.time.LocalDate;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.test.context.junit4.SpringRunner;
import static org.junit.Assert.assertEquals;

@RunWith(SpringRunner.class)
public class Visit_setDate_c4566f8342_Test {

    private Visit visit;

    @Before
    public void setup() {
        visit = new Visit();
    }

    @Test
    public void testSetDateWithValidDate() {
        LocalDate testDate = LocalDate.of(2022, 12, 12);
        visit.setDate(testDate);
        assertEquals(testDate, visit.getDate());
    }

    @Test
    public void testSetDateWithNull() {
        visit.setDate(null);
        assertEquals(null, visit.getDate());
    }
}
