// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import static org.mockito.Mockito.mock;
import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.samples.petclinic.owner.OwnerRepository;
import org.springframework.samples.petclinic.owner.VisitController;

class VisitController_VisitController_1785f2ab4c_Test {

    private OwnerRepository owners;
    private VisitController visitController;

    @BeforeEach
    void setUp() {
        owners = mock(OwnerRepository.class);
        visitController = new VisitController(owners);
    }

    @Test
    void testVisitController() {
        assertEquals(owners, visitController.getOwners());
    }

    @Test
    void testVisitControllerNull() {
        VisitController visitControllerNull = new VisitController(null);
        assertEquals(null, visitControllerNull.getOwners());
    }
}
