// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import java.time.LocalDate;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.samples.petclinic.model.BaseEntity;

public class Visit_setDate_c4566f8342_Test {

    private BaseEntity baseEntity;

    @BeforeEach
    public void setup() {
        baseEntity = new BaseEntity();
    }

    @Test
    public void testSetDateSuccess() {
        LocalDate expectedDate = LocalDate.now();
        baseEntity.setDate(expectedDate);
        LocalDate actualDate = baseEntity.getDate();
        Assertions.assertEquals(expectedDate, actualDate);
    }

    @Test
    public void testSetDateNull() {
        baseEntity.setDate(null);
        LocalDate actualDate = baseEntity.getDate();
        Assertions.assertNull(actualDate);
    }
}
