// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import org.junit.jupiter.api.Test;
import org.springframework.samples.petclinic.model.Visit;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class Visit_getDescription_b1844ea396_Test {

    @Test
    public void testGetDescription() {
        // Arrange
        Visit visit = new Visit();
        String expectedDescription = "Regular Checkup";
        visit.setDescription(expectedDescription);
        
        // Act
        String actualDescription = visit.getDescription();

        // Assert
        assertEquals(expectedDescription, actualDescription, "Expected and actual descriptions should match");
    }

    @Test
    public void testGetDescriptionWhenDescriptionIsNull() {
        // Arrange
        Visit visit = new Visit();
        String expectedDescription = null;
        visit.setDescription(expectedDescription);

        // Act
        String actualDescription = visit.getDescription();

        // Assert
        assertEquals(expectedDescription, actualDescription, "Expected and actual descriptions should match when description is null");
    }
}
