// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit.jupiter.SpringExtension;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.mock;

@ExtendWith(SpringExtension.class)
@SpringBootTest
public class VisitController_initNewVisitForm_de58f9a1b2_Test {

    @Autowired
    private VisitController visitController;

    @Test
    public void testInitNewVisitForm_success() {
        String viewName = visitController.initNewVisitForm();
        assertEquals("pets/createOrUpdateVisitForm", viewName);
    }

    @Test
    public void testInitNewVisitForm_failure() {
        String viewName = visitController.initNewVisitForm();
        assertEquals("pets/wrongForm", viewName);
    }
}
