// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

public class VisitController_VisitController_1785f2ab4c_Test {

    @Mock
    private OwnerRepository owners;

    private VisitController visitController;

    @BeforeEach
    public void setup() {
        MockitoAnnotations.initMocks(this);
        visitController = new VisitController(owners);
    }

    @Test
    public void testVisitController() {
        OwnerRepository ownerMock = mock(OwnerRepository.class);
        VisitController visitController = new VisitController(ownerMock);
        assertEquals(ownerMock, visitController.getOwners());
    }

    @Test
    public void testVisitController_NullOwner() {
        VisitController visitController = new VisitController(null);
        assertEquals(null, visitController.getOwners());
    }
}
