// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.mockito.Mockito.when;

public class VisitController_VisitController_1785f2ab4c_Test {

    @Mock
    private OwnerRepository owners;

    @InjectMocks
    private VisitController visitController;

    @BeforeEach
    public void init() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testVisitController() {
        when(owners.findById(1)).thenReturn(new Owner());
        assertNotNull(visitController);
    }

    @Test
    public void testVisitController_NullOwner() {
        when(owners.findById(1)).thenReturn(null);
        assertNotNull(visitController);
    }
}
