// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.samples.petclinic.model.BaseEntity;

class Visit_setDescription_b4ccff923c_Test {

    private BaseEntity visit;

    @BeforeEach
    void setUp() {
        visit = new BaseEntity();
    }

    @Test
    void testSetDescription_ValidDescription() {
        String validDescription = "This is a valid description.";
        visit.setDescription(validDescription);
        assertEquals(validDescription, visit.getDescription(), "The description should match the set value.");
    }

    @Test
    void testSetDescription_NullDescription() {
        String nullDescription = null;
        assertThrows(NullPointerException.class, () -> visit.setDescription(nullDescription), "Setting description to null should throw NullPointerException.");
    }

    @Test
    void testSetDescription_EmptyDescription() {
        String emptyDescription = "";
        visit.setDescription(emptyDescription);
        assertEquals(emptyDescription, visit.getDescription(), "The description should match the set value even if it is empty.");
    }
}
