// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.validation.BeanPropertyBindingResult;

public class VisitController_processNewVisitForm_7a4a412d78_Test {

    private Owner owner;
    private Visit visit;
    private BindingResult result;
    private Owners owners;
    private final int petId = 1;

    @BeforeEach
    public void setup() {
        owner = mock(Owner.class);
        visit = mock(Visit.class);
        owners = mock(Owners.class);
        result = new BeanPropertyBindingResult(visit, "visit");
    }

    @Test
    public void testProcessNewVisitForm_WithErrors() {
        result.reject("error");

        String view = new VisitController(owners).processNewVisitForm(owner, petId, visit, result);

        assertEquals("pets/createOrUpdateVisitForm", view);
    }

    @Test
    public void testProcessNewVisitForm_WithoutErrors() {
        when(owner.addVisit(petId, visit)).thenReturn(visit);

        String view = new VisitController(owners).processNewVisitForm(owner, petId, visit, result);

        assertEquals("redirect:/owners/{ownerId}", view);
        verify(owner).addVisit(petId, visit);
        verify(owners).save(owner);
    }
}
