// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.system;

import org.springframework.boot.autoconfigure.cache.JCacheManagerCustomizer;
import org.springframework.cache.annotation.EnableCaching;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import javax.cache.configuration.MutableConfiguration;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import static org.mockito.Mockito.verify;

@Configuration
@EnableCaching
@ExtendWith(MockitoExtension.class)
public class CacheConfiguration_petclinicCacheConfigurationCustomizer_adca9b283f_Test {

    @Mock
    MutableConfiguration cacheConfiguration;
    
    @InjectMocks
    CacheConfiguration cacheConfig;
    
    @Test
    public void testPetclinicCacheConfigurationCustomizer_Success() {
        JCacheManagerCustomizer customizer = cacheConfig.petclinicCacheConfigurationCustomizer();
        customizer.customize(null);
        verify(cacheConfiguration).createCache("vets", cacheConfiguration);
    }

    @Test
    public void testPetclinicCacheConfigurationCustomizer_Failure() {
        JCacheManagerCustomizer customizer = cacheConfig.petclinicCacheConfigurationCustomizer();
        customizer.customize(null);
        verify(cacheConfiguration).createCache("notVets", cacheConfiguration);
    }
}
