// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.system;

import org.springframework.boot.autoconfigure.cache.JCacheManagerCustomizer;
import org.springframework.cache.annotation.EnableCaching;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import javax.cache.configuration.MutableConfiguration;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import javax.cache.configuration.Configuration;

@Configuration
@EnableCaching
public class CacheConfiguration_cacheConfiguration_2463e86670_Test {

    private Configuration<Object, Object> cacheConfiguration() {
        return new MutableConfiguration<>().setStatisticsEnabled(true);
    }

    @Test
    public void testCacheConfiguration() {
        Configuration<Object, Object> configuration = cacheConfiguration();
        Assertions.assertNotNull(configuration);
        Assertions.assertTrue(configuration.isStatisticsEnabled());
    }

    @Test
    public void testCacheConfigurationFailure() {
        Configuration<Object, Object> configuration = cacheConfiguration();
        Assertions.assertNotNull(configuration);
        Assertions.assertFalse(!configuration.isStatisticsEnabled());
    }
}
