// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.system;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.boot.autoconfigure.cache.JCacheManagerCustomizer;
import org.springframework.cache.annotation.EnableCaching;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import javax.cache.configuration.MutableConfiguration;

import static org.junit.jupiter.api.Assertions.*;

@Configuration
@EnableCaching
public class CacheConfiguration_cacheConfiguration_2463e86670_Test {

    private MutableConfiguration<Object, Object> cacheConfiguration;

    @BeforeEach
    public void setUp() {
        cacheConfiguration = new MutableConfiguration<>().setStatisticsEnabled(true);
    }

    @Test
    public void testCacheConfiguration() {
        assertNotNull(cacheConfiguration);
        assertTrue(cacheConfiguration.isStatisticsEnabled());
    }

    @Test
    public void testCacheConfigurationFailure() {
        cacheConfiguration = new MutableConfiguration<>().setStatisticsEnabled(false);
        assertFalse(cacheConfiguration.isStatisticsEnabled());
    }
}
