// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.system;

import org.springframework.boot.autoconfigure.cache.JCacheManagerCustomizer;
import org.springframework.cache.annotation.EnableCaching;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import javax.cache.configuration.MutableConfiguration;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

@Configuration
@EnableCaching
public class CacheConfiguration_cacheConfiguration_2463e86670_Test {

    private Configuration<Object, Object> cacheConfiguration() {
        return new MutableConfiguration<>().setStatisticsEnabled(true);
    }
    
    @Test
    public void testCacheConfiguration_WithStatisticsEnabled() {
        Configuration<Object, Object> config = cacheConfiguration();
        assertTrue(config.isStatisticsEnabled());
    }

    @Test
    public void testCacheConfiguration_WithoutStatisticsEnabled() {
        Configuration<Object, Object> config = new MutableConfiguration<>();
        assertFalse(config.isStatisticsEnabled());
    }
}
