// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.system;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.samples.petclinic.system.CrashController;

import static org.junit.jupiter.api.Assertions.assertThrows;

@ExtendWith(MockitoExtension.class)
public class CrashController_triggerException_bed1c282fb_Test {

    @InjectMocks
    CrashController crashController;

    @Test
    public void testTriggerException_RuntimeException() {
        Exception exception = assertThrows(RuntimeException.class, () -> {
            crashController.triggerException();
        });

        String expectedMessage = "Expected: controller used to showcase what happens when an exception is thrown";
        String actualMessage = exception.getMessage();

        assertEquals(expectedMessage, actualMessage);
    }

    @Test
    public void testTriggerException_NullPointerException() {
        Exception exception = assertThrows(NullPointerException.class, () -> {
            crashController.triggerException();
        });

        String expectedMessage = "Expected: controller used to showcase what happens when an exception is thrown";
        String actualMessage = exception.getMessage();

        assertNotEquals(expectedMessage, actualMessage);
    }
}
