// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.system;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.samples.petclinic.system.CrashController;

import static org.junit.jupiter.api.Assertions.assertThrows;

@SpringBootTest
public class CrashController_triggerException_bed1c282fb_Test {

    @Test
    public void testTriggerExceptionMessage() {
        CrashController crashController = new CrashController();
        Exception exception = assertThrows(RuntimeException.class, () -> {
            crashController.triggerException();
        });

        String expectedMessage = "Expected: controller used to showcase what happens when an exception is thrown";
        String actualMessage = exception.getMessage();

        assertEquals(expectedMessage, actualMessage);
    }

    @Test
    public void testTriggerExceptionType() {
        CrashController crashController = new CrashController();
        assertThrows(RuntimeException.class, () -> {
            crashController.triggerException();
        });
    }
}
