// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.system;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit4.SpringRunner;
import static org.junit.Assert.assertTrue;

@RunWith(SpringRunner.class)
@SpringBootTest
public class CrashController_triggerException_bed1c282fb_Test {

    @Test(expected = RuntimeException.class)
    public void testTriggerException() {
        CrashController crashController = new CrashController();
        crashController.triggerException();
    }

    @Test
    public void testTriggerExceptionMessage() {
        CrashController crashController = new CrashController();
        try {
            crashController.triggerException();
        } catch (RuntimeException e) {
            assertTrue(e.getMessage().contains("Expected: controller used to showcase what happens when an exception is thrown"));
        }
    }
}
