// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.system;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

@Controller
public class WelcomeController_welcome_404fffca92_Test {

    private WelcomeController controller;

    @BeforeEach
    public void setup() {
        controller = new WelcomeController();
    }

    @Test
    public void testWelcome() {
        String expected = "welcome";
        String actual = controller.welcome();
        assertEquals(expected, actual);
    }

    @Test
    public void testWelcomeFailure() {
        String unexpected = "not_welcome";
        String actual = controller.welcome();
        assertNotEquals(unexpected, actual);
    }
}
