// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.model;

import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

public class BaseEntity_setId_fdd9d7675d_Test {

    private BaseEntity baseEntity;

    @BeforeEach
    public void setUp() {
        baseEntity = new BaseEntity();
    }

    @Test
    public void setId_ValidId_Success() {
        Integer id = 10;
        baseEntity.setId(id);
        assertEquals(id, baseEntity.getId(), "The ID set does not match the ID retrieved");
    }

    @Test
    public void setId_NullId_Success() {
        baseEntity.setId(null);
        assertEquals(null, baseEntity.getId(), "The ID set does not match the ID retrieved");
    }
}
