// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.MockitoAnnotations;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;

public class BaseEntity_getId_2f24a803f0_Test {
    BaseEntity baseEntity;

    @BeforeEach
    public void setup() {
        MockitoAnnotations.initMocks(this);
        baseEntity = new BaseEntity();
    }

    @Test
    public void testGetIdReturnsNullWhenNotSet() {
        assertNull(baseEntity.getId(), "When id is not set, getId() should return null");
    }

    @Test
    public void testGetIdReturnsCorrectValueWhenSet() {
        Integer expectedId = 123;
        baseEntity.setId(expectedId);
        assertEquals(expectedId, baseEntity.getId(), "When id is set, getId() should return the correct value");
    }
}
