// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.model;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

public class BaseEntity_getId_2f24a803f0_Test {

    private BaseEntity baseEntity;

    @BeforeEach
    public void setup() {
        baseEntity = new BaseEntity();
    }

    @Test
    public void testGetIdWhenIdIsNull() {
        Integer id = baseEntity.getId();
        assertNull(id, "Expected id to be null");
    }

    @Test
    public void testGetIdWhenIdIsNotNull() {
        Integer expectedId = 123;
        baseEntity.setId(expectedId);
        Integer actualId = baseEntity.getId();
        assertEquals(expectedId, actualId, "Expected id to be " + expectedId);
    }
}
