// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.model;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

public class BaseEntity_isNew_9b282f7a8e_Test {

    @Test
    public void testIsNew_idIsNull() {
        BaseEntity testBaseEntity = new BaseEntity();
        testBaseEntity.setId(null);
        Assertions.assertTrue(testBaseEntity.isNew(), "isNew should return true when id is null");
    }

    @Test
    public void testIsNew_idIsNotNull() {
        BaseEntity testBaseEntity = new BaseEntity();
        testBaseEntity.setId(1);
        Assertions.assertFalse(testBaseEntity.isNew(), "isNew should return false when id is not null");
    }
}
