// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class BaseEntity_setId_fdd9d7675d_Test {

    private BaseEntity baseEntity;

    @BeforeEach
    public void setUp() {
        baseEntity = new BaseEntity();
    }

    @Test
    public void testSetId() {
        Integer id = 10;
        baseEntity.setId(id);
        assertEquals(id, baseEntity.getId());
    }

    @Test
    public void testSetIdWithNull() {
        baseEntity.setId(null);
        assertEquals(null, baseEntity.getId());
    }
}
