// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.model;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

public class BaseEntity_setId_fdd9d7675d_Test {

  private BaseEntity baseEntity;

  @BeforeEach
  public void setUp() {
    baseEntity = new BaseEntity();
  }

  @Test
  public void testSetId_Success() {
    Integer id = 1;
    baseEntity.setId(id);
    assertEquals(id, baseEntity.getId(), "The set Id does not match the expected Id");
  }

  @Test
  public void testSetId_Null() {
    baseEntity.setId(null);
    assertNull(baseEntity.getId(), "The Id should be null");
  }

}
