// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.model;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.junit.jupiter.MockitoExtension;

import static org.junit.jupiter.api.Assertions.assertEquals;

@ExtendWith(MockitoExtension.class)
public class BaseEntity_getId_2f24a803f0_Test {
    
    @InjectMocks
    private BaseEntity baseEntity;
    
    @BeforeEach
    public void init() {
        baseEntity = new BaseEntity();
    }

    @Test
    public void testGetId_whenIdIsNull() {
        baseEntity.setId(null);
        Integer expected = null;
        Integer actual = baseEntity.getId();
        assertEquals(expected, actual, "Expected null but actual is not null");
    }
    
    @Test
    public void testGetId_whenIdIsNotNull() {
        baseEntity.setId(123);
        Integer expected = 123;
        Integer actual = baseEntity.getId();
        assertEquals(expected, actual, "Expected and actual id do not match");
    }
}
