// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.model;

import jakarta.persistence.Column;
import jakarta.persistence.MappedSuperclass;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

@MappedSuperclass
public class NamedEntity_setName_5d23a892d9_Test {

    private NamedEntity namedEntity;

    @BeforeEach
    public void setup() {
        namedEntity = new NamedEntity();
    }

    @Test
    public void setName_ValidInput_ExpectSuccess() {
        String expectedName = "TestName";
        namedEntity.setName(expectedName);
        assertEquals(expectedName, namedEntity.getName());
    }

    @Test
    public void setName_NullInput_ExpectNull() {
        namedEntity.setName(null);
        assertEquals(null, namedEntity.getName());
    }

    @Column(name = "name")
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }
}
