// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.model;

import static org.junit.Assert.assertEquals;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit4.SpringRunner;

@RunWith(SpringRunner.class)
@SpringBootTest
public class NamedEntity_toString_ceffa8036e_Test {

  @Test
  public void testToString_withValidName() {
    NamedEntity namedEntity = new NamedEntity();
    namedEntity.setName("Test Name");
    String result = namedEntity.toString();
    assertEquals("Test Name", result);
  }

  @Test
  public void testToString_withEmptyName() {
    NamedEntity namedEntity = new NamedEntity();
    namedEntity.setName("");
    String result = namedEntity.toString();
    assertEquals("", result);
  }

  @Test
  public void testToString_withNullName() {
    NamedEntity namedEntity = new NamedEntity();
    namedEntity.setName(null);
    String result = namedEntity.toString();
    assertEquals(null, result);
  }
}
