// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.model;

import jakarta.persistence.Column;
import jakarta.persistence.MappedSuperclass;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;

@MappedSuperclass
public class NamedEntity_setName_5d23a892d9_Test {

    private NamedEntity namedEntity;

    @BeforeEach
    public void setUp() {
        namedEntity = Mockito.mock(NamedEntity.class);
    }

    @Test
    public void testSetName() {
        String testName = "Test Name";
        Mockito.doAnswer(invocation -> {
            Object arg0 = invocation.getArgument(0);
            Assertions.assertEquals(testName, arg0);
            return null;
        }).when(namedEntity).setName(Mockito.anyString());

        namedEntity.setName(testName);
    }

    @Test
    public void testSetName_Null() {
        String testName = null;
        Mockito.doAnswer(invocation -> {
            Object arg0 = invocation.getArgument(0);
            Assertions.assertNull(arg0);
            return null;
        }).when(namedEntity).setName(Mockito.anyString());

        namedEntity.setName(testName);
    }
}
