// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.model;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;
import static org.junit.jupiter.api.Assertions.assertEquals;

@SpringBootTest
public class NamedEntity_toString_ceffa8036e_Test {

    @Test
    public void testToString() {
        NamedEntity namedEntity = new NamedEntity();
        namedEntity.setName("Test Name");
        assertEquals("Test Name", namedEntity.toString());
    }

    @Test
    public void testToStringWithEmptyName() {
        NamedEntity namedEntity = new NamedEntity();
        namedEntity.setName("");
        assertEquals("", namedEntity.toString());
    }

    @Test
    public void testToStringWithNullName() {
        NamedEntity namedEntity = new NamedEntity();
        namedEntity.setName(null);
        assertEquals(null, namedEntity.toString());
    }
}
