// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class NamedEntity_getName_8400ac6fb7_Test {

    private NamedEntity namedEntity;

    @BeforeEach
    public void setUp() {
        namedEntity = new NamedEntity();
    }

    @Test
    public void testGetName_whenNameIsSet_thenShouldReturnSameName() {
        String expectedName = "Test Name";
        namedEntity.setName(expectedName);

        String actualName = namedEntity.getName();

        assertEquals(expectedName, actualName, "The expected name did not match the actual name");
    }

    @Test
    public void testGetName_whenNameIsNotSet_thenShouldReturnNull() {
        String actualName = namedEntity.getName();

        assertEquals(null, actualName, "The expected name did not match the actual name");
    }
}
