// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.model;

import jakarta.persistence.Column;
import jakarta.persistence.MappedSuperclass;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

@MappedSuperclass
public class NamedEntity_getName_8400ac6fb7_Test {

  @Column(name = "name")
  private String name;

  @BeforeEach
  public void setUp() {
    this.name = "TestName";
  }

  public String getName() {
    return this.name;
  }

  @Test
  public void testGetName() {
    String expectedName = "TestName";
    String actualName = getName();
    assertEquals(expectedName, actualName, "Failed - expected name does not match actual name");
  }

  @Test
  public void testGetNameFailure() {
    String expectedName = "WrongTestName";
    String actualName = getName();
    assertEquals(expectedName, actualName, "Failed - expected name does not match actual name");
  }
}
