// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.model;

import org.junit.Before;
import org.junit.Test;
import static org.junit.Assert.assertEquals;

public class NamedEntity_getName_8400ac6fb7_Test {

    private NamedEntity namedEntity;

    @Before
    public void setUp() {
        namedEntity = new NamedEntity();
    }

    @Test
    public void testGetNameWhenNameIsSet() {
        String expectedName = "Test Name";
        namedEntity.setName(expectedName);
        assertEquals(expectedName, namedEntity.getName());
    }

    @Test
    public void testGetNameWhenNameIsNotSet() {
        assertEquals(null, namedEntity.getName());
    }
}
