// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import org.springframework.samples.petclinic.model.NamedEntity;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.when;

public class NamedEntity_toString_ceffa8036e_Test {

    @Mock
    private NamedEntity namedEntity;

    @BeforeEach
    public void setup() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testToStringWhenNameIsNull() {
        when(namedEntity.getName()).thenReturn(null);
        String result = namedEntity.toString();
        assertEquals(null, result);
    }

    @Test
    public void testToStringWhenNameIsNotEmpty() {
        String expectedName = "Test Name";
        when(namedEntity.getName()).thenReturn(expectedName);
        String result = namedEntity.toString();
        assertEquals(expectedName, result);
    }
}
