// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.model;

import jakarta.persistence.Column;
import jakarta.persistence.MappedSuperclass;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.mock.mockito.MockBean;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

@SpringBootTest
public class NamedEntity_setName_5d23a892d9_Test {

    @MockBean
    private NamedEntity namedEntity;

    @BeforeEach
    public void setUp() {
        namedEntity = new NamedEntity();
    }

    @Test
    public void testSetName() {
        String name = "John Doe";
        namedEntity.setName(name);
        assertEquals(name, namedEntity.getName(), "The name should be set correctly");
    }

    @Test
    public void testSetName_Null() {
        assertThrows(NullPointerException.class, () -> {
            namedEntity.setName(null);
        }, "Setting name as null should throw NullPointerException");
    }
}
