// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.model;

import jakarta.validation.constraints.NotBlank;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.junit.jupiter.MockitoExtension;

@ExtendWith(MockitoExtension.class)
public class Person_setFirstName_8acaec2cfc_Test {

    Person person;

    @BeforeEach
    public void setup() {
        person = new Person();
    }

    @Test
    public void testSetFirstNameSuccess() {
        String firstName = "John";
        person.setFirstName(firstName);
        Assertions.assertEquals(firstName, person.getFirstName());
    }

    @Test
    public void testSetFirstNameWithNull() {
        String firstName = null;
        person.setFirstName(firstName);
        Assertions.assertNull(person.getFirstName());
    }
}
