// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.model;

import static org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.mock.mockito.MockBean;

@SpringBootTest
public class Person_getFirstName_94e06d272a_Test {

    @MockBean
    private Person person;

    @BeforeEach
    public void setup() {
        Mockito.when(person.getFirstName()).thenReturn("John");
    }

    @Test
    public void testGetFirstName() {
        String firstName = person.getFirstName();
        assertEquals("John", firstName);
    }

    @Test
    public void testGetFirstNameFailure() {
        Mockito.when(person.getFirstName()).thenReturn(null);
        String firstName = person.getFirstName();
        assertEquals(null, firstName);
    }
}
