// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.model;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;

import jakarta.persistence.Column;
import jakarta.persistence.MappedSuperclass;
import jakarta.validation.constraints.NotBlank;

@MappedSuperclass
public class Person_setLastName_4141db5e7c_Test {

    private Person person;

    @BeforeEach
    public void setUp() {
        person = Mockito.mock(Person.class);
    }

    @Test
    public void testSetLastName() {
        String lastName = "Smith";
        Mockito.doAnswer(invocation -> {
            String argument = invocation.getArgument(0);
            Assertions.assertEquals(lastName, argument);
            return null;
        }).when(person).setLastName(Mockito.anyString());

        person.setLastName(lastName);
    }

    @Test
    public void testSetLastNameNull() {
        String lastName = null;
        Mockito.doAnswer(invocation -> {
            String argument = invocation.getArgument(0);
            Assertions.assertNull(argument);
            return null;
        }).when(person).setLastName(Mockito.anyString());

        person.setLastName(lastName);
    }

    @Test
    public void testSetLastNameBlank() {
        String lastName = "";
        Mockito.doAnswer(invocation -> {
            String argument = invocation.getArgument(0);
            Assertions.assertEquals(lastName, argument);
            return null;
        }).when(person).setLastName(Mockito.anyString());

        person.setLastName(lastName);
    }
}
