// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.model;

import jakarta.persistence.Column;
import jakarta.persistence.MappedSuperclass;
import jakarta.validation.constraints.NotBlank;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

@MappedSuperclass
public class Person_getLastName_4814a2dee7_Test {

    private Person person;

    @BeforeEach
    public void setup() {
        person = new Person();
    }

    @Test
    public void testGetLastName_Success() {
        String expectedLastName = "Doe";
        person.setLastName(expectedLastName);
        String actualLastName = person.getLastName();
        assertEquals(expectedLastName, actualLastName);
    }

    @Test
    public void testGetLastName_Null() {
        person.setLastName(null);
        String actualLastName = person.getLastName();
        assertEquals(null, actualLastName);
    }
}
