// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;

import static org.junit.jupiter.api.Assertions.*;

@SpringBootTest
public class Person_setLastName_4141db5e7c_Test {

    private Person person;

    @BeforeEach
    public void setup() {
        person = new Person();
    }

    @Test
    public void testSetLastName() {
        String expectedLastName = "Doe";
        person.setLastName(expectedLastName);
        assertEquals(expectedLastName, person.getLastName());
    }

    @Test
    public void testSetLastName_Null() {
        String expectedLastName = null;
        person.setLastName(expectedLastName);
        assertEquals(expectedLastName, person.getLastName());
    }

    // TODO: Add more test cases if needed
}
