// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.model;

import static org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

public class Person_getFirstName_94e06d272a_Test {

    private Person person;

    @BeforeEach
    public void setup() {
        person = new Person();
    }

    @Test
    public void testGetFirstName_WhenNameIsJohn() {
        person.setFirstName("John");
        String firstName = person.getFirstName();
        assertEquals("John", firstName, "Expected name is John but got " + firstName);
    }

    @Test
    public void testGetFirstName_WhenNameIsEmpty() {
        person.setFirstName("");
        String firstName = person.getFirstName();
        assertEquals("", firstName, "Expected name is empty but got " + firstName);
    }

    // TODO: add your test case here
}
