// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.model;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;
import static org.junit.jupiter.api.Assertions.assertEquals;

@SpringBootTest
public class Person_getFirstName_94e06d272a_Test {

    @Test
    public void testGetFirstName() {
        Person person = new Person();
        person.setFirstName("John");
        assertEquals("John", person.getFirstName());
    }

    @Test
    public void testGetFirstName_Empty() {
        Person person = new Person();
        person.setFirstName("");
        assertEquals("", person.getFirstName());
    }

    @Test
    public void testGetFirstName_Null() {
        Person person = new Person();
        person.setFirstName(null);
        assertEquals(null, person.getFirstName());
    }
}
