// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.model;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;
import static org.junit.jupiter.api.Assertions.assertEquals;

@SpringBootTest
public class Person_setFirstName_8acaec2cfc_Test {

    @Test
    public void testSetFirstName() {
        Person person = new Person();
        person.setFirstName("John");
        assertEquals("John", person.getFirstName());
    }

    @Test
    public void testSetFirstNameWithNull() {
        Person person = new Person();
        person.setFirstName(null);
        assertEquals(null, person.getFirstName());
    }
}
