// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.model;

import jakarta.persistence.Column;
import jakarta.persistence.MappedSuperclass;
import jakarta.validation.constraints.NotBlank;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import org.springframework.boot.test.context.SpringBootTest;
import static org.junit.jupiter.api.Assertions.assertEquals;

@SpringBootTest
public class Person_getLastName_4814a2dee7_Test {

    private Person person;

    @BeforeEach
    public void setup() {
        person = new Person();
        person.setLastName("Smith");
    }

    @Test
    public void testGetLastName_success() {
        String expected = "Smith";
        String actual = person.getLastName();
        assertEquals(expected, actual, "The last name should be Smith");
    }

    @Test
    public void testGetLastName_failure() {
        String expected = "Johnson";
        String actual = person.getLastName();
        assertEquals(expected, actual, "The last name should not match");
    }
}
