// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import org.springframework.aot.hint.RuntimeHints;
import org.springframework.samples.petclinic.model.BaseEntity;
import org.springframework.samples.petclinic.model.Person;
import org.springframework.samples.petclinic.vet.Vet;

import static org.mockito.Mockito.*;

class PetClinicRuntimeHints_registerHints_6d9943ba0f_Test {

    @Mock
    RuntimeHints hints;

    @InjectMocks
    PetClinicRuntimeHints_registerHints_6d9943ba0f petClinicRuntimeHints_registerHints_6d9943ba0f;

    @BeforeEach
    void setUp() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    void testRegisterHints() {
        ClassLoader classLoader = mock(ClassLoader.class);
        petClinicRuntimeHints_registerHints_6d9943ba0f.registerHints(hints, classLoader);
        verify(hints, times(1)).resources().registerPattern("db/*");
        verify(hints, times(1)).resources().registerPattern("messages/*");
        verify(hints, times(1)).resources().registerPattern("META-INF/resources/webjars/*");
        verify(hints, times(1)).resources().registerPattern("mysql-default-conf");
        verify(hints, times(1)).serialization().registerType(BaseEntity.class);
        verify(hints, times(1)).serialization().registerType(Person.class);
        verify(hints, times(1)).serialization().registerType(Vet.class);
    }
}
