// Test generated by RoostGPT for test aps-java-pet using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.aot.hint.RuntimeHints;
import org.springframework.samples.petclinic.model.BaseEntity;
import org.springframework.samples.petclinic.model.Person;
import org.springframework.samples.petclinic.vet.Vet;

import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.times;

@ExtendWith(MockitoExtension.class)
public class PetClinicRuntimeHints_registerHints_6d9943ba0f_Test {

    @Mock
    private RuntimeHints hints;

    private PetClinicRuntimeHints_registerHints_6d9943ba0f runtimeHints;

    @BeforeEach
    public void setup() {
        runtimeHints = new PetClinicRuntimeHints_registerHints_6d9943ba0f();
    }

    @Test
    public void testRegisterHints() {
        runtimeHints.registerHints(hints, Thread.currentThread().getContextClassLoader());

        verify(hints, times(1)).resources().registerPattern("db/*");
        verify(hints, times(1)).resources().registerPattern("messages/*");
        verify(hints, times(1)).resources().registerPattern("META-INF/resources/webjars/*");
        verify(hints, times(1)).resources().registerPattern("mysql-default-conf");
        verify(hints, times(1)).serialization().registerType(BaseEntity.class);
        verify(hints, times(1)).serialization().registerType(Person.class);
        verify(hints, times(1)).serialization().registerType(Vet.class);
    }
}
